--- 
title: "Bayesian models in R and Python"
author: "Kristin Broms"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a tutorial for R users to convert their code into Python. In particular, fitting GLMMs, hierchical BAyesian models, and non-linear Bayesian models."
---

# Introduction

I have used R, in conjunction with Rmarkdown documents, in an RStudio GUI for over a decade. It is a beautiful setup, with great work flows and clean coding. It is perfect for non-production level analyses, visualizations, interactive documents, web apps, and reports.

However, the world seems to prefer Python. Perhaps it is because computer programmers rule the world more than statisticians and scientists. In that vein, I am writing this tutorial to fit Bayesian GLMM's and non-linear models in Python. 

All models are written mathematically and fit in both R and Python. Frequentist versions are fit, when available, in addition to the Bayesian versions. There are four chapters: GLMM's in R; GLMM's in Python; non-linear models in R; and non-linear models in Python.

This particular webpage/chapter fits GLMM's in R. The "GLMM's in Python" has parallel text and code chunks to easily see how commands correspond between the different software.


## Case Study



## Case study objectives

How well does the treatment work?


At each location, there is one rice field that is a control group and one rice field that is treated with pheromones. **The objective is to determine how good the treatment is at reducing moth populations. This is measured as a reduction of moth counts in the traps in the treatment fields compared to the traps in the control fields.**

The performance metric of interest is trap reduction (TR), which is a derived parameter of the regression coefficient:

$$
TR = 100 - 100 e ^{(-\beta_1)}
$$

If trapping reduction were 100%, no moths would ever be caught in the treatment traps. However, some random moths will inevitably land in any trap. Instead, product performance is considered good if 90% trapping reduction is achieved, meaning that 90% fewer moths are caught in the treatment traps. When trapping reduction goes below 0%, the parameter no longer makes sense and cannot be interpreted.

It should also be noted that treatment performance may decline over time. Perhaps there is not enough pheromone to last for the entire season, or the ecosystem may change during the season in a way that somehow lessens product performance (e.g., the pheromones from the plants may change and interact with the product.)

