<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 GLMM’s in Python | Bayesian models in R and Python</title>
  <meta name="description" content="This is a tutorial for R users to convert their code into Python. In particular, fitting GLMMs, hierchical BAyesian models, and non-linear Bayesian models." />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 GLMM’s in Python | Bayesian models in R and Python" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a tutorial for R users to convert their code into Python. In particular, fitting GLMMs, hierchical BAyesian models, and non-linear Bayesian models." />
  <meta name="github-repo" content="rstudio/BayesInPython" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 GLMM’s in Python | Bayesian models in R and Python" />
  
  <meta name="twitter:description" content="This is a tutorial for R users to convert their code into Python. In particular, fitting GLMMs, hierchical BAyesian models, and non-linear Bayesian models." />
  

<meta name="author" content="Kristin Broms" />


<meta name="date" content="2025-07-03" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="GLMMsR.html"/>
<link rel="next" href="NonlinearR.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#CaseStudy"><i class="fa fa-check"></i><b>1.1</b> Case Study</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#case-study-objectives"><i class="fa fa-check"></i><b>1.1.1</b> Case study objectives</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="mathematical-models.html"><a href="mathematical-models.html"><i class="fa fa-check"></i><b>2</b> Mathematical models</a>
<ul>
<li class="chapter" data-level="2.1" data-path="mathematical-models.html"><a href="mathematical-models.html#glm"><i class="fa fa-check"></i><b>2.1</b> GLM models</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="mathematical-models.html"><a href="mathematical-models.html#poisson-regression-model"><i class="fa fa-check"></i><b>2.1.1</b> Poisson regression model</a></li>
<li class="chapter" data-level="2.1.2" data-path="mathematical-models.html"><a href="mathematical-models.html#negative-binomial-regression-model"><i class="fa fa-check"></i><b>2.1.2</b> Negative binomial regression model</a></li>
<li class="chapter" data-level="2.1.3" data-path="mathematical-models.html"><a href="mathematical-models.html#bayesian-model"><i class="fa fa-check"></i><b>2.1.3</b> Bayesian model</a></li>
<li class="chapter" data-level="2.1.4" data-path="mathematical-models.html"><a href="mathematical-models.html#trapping-reduction-defined"><i class="fa fa-check"></i><b>2.1.4</b> Trapping reduction defined</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="mathematical-models.html"><a href="mathematical-models.html#glmm"><i class="fa fa-check"></i><b>2.2</b> GLMM: Random effects (RE) for locations</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="mathematical-models.html"><a href="mathematical-models.html#glmm-mathematical-model"><i class="fa fa-check"></i><b>2.2.1</b> GLMM mathematical model</a></li>
<li class="chapter" data-level="2.2.2" data-path="mathematical-models.html"><a href="mathematical-models.html#bayesian-version"><i class="fa fa-check"></i><b>2.2.2</b> Bayesian version</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="mathematical-models.html"><a href="mathematical-models.html#glmm-dates"><i class="fa fa-check"></i><b>2.3</b> GLMM: RE for Location, SamplingDate</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="mathematical-models.html"><a href="mathematical-models.html#frequentist-version"><i class="fa fa-check"></i><b>2.3.1</b> Frequentist version</a></li>
<li class="chapter" data-level="2.3.2" data-path="mathematical-models.html"><a href="mathematical-models.html#bayesian-version-1"><i class="fa fa-check"></i><b>2.3.2</b> Bayesian version</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="mathematical-models.html"><a href="mathematical-models.html#glmm-gp"><i class="fa fa-check"></i><b>2.4</b> GLMM with Gaussian Processes: RE for Trial, GP for Date</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="mathematical-models.html"><a href="mathematical-models.html#bayesian-mathematical-model"><i class="fa fa-check"></i><b>2.4.1</b> Bayesian mathematical model</a></li>
<li class="chapter" data-level="2.4.2" data-path="mathematical-models.html"><a href="mathematical-models.html#gaussian-process-bayes-brms-version"><i class="fa fa-check"></i><b>2.4.2</b> Gaussian Process Bayes (brms) version</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="GLMMsR.html"><a href="GLMMsR.html"><i class="fa fa-check"></i><b>3</b> GLMM’s in R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="GLMMsR.html"><a href="GLMMsR.html#setup"><i class="fa fa-check"></i><b>3.1</b> Setup</a></li>
<li class="chapter" data-level="3.2" data-path="GLMMsR.html"><a href="GLMMsR.html#data-exploration"><i class="fa fa-check"></i><b>3.2</b> Data exploration</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="GLMMsR.html"><a href="GLMMsR.html#the-data"><i class="fa fa-check"></i><b>3.2.1</b> The data</a></li>
<li class="chapter" data-level="3.2.2" data-path="GLMMsR.html"><a href="GLMMsR.html#moth-counts-plotted"><i class="fa fa-check"></i><b>3.2.2</b> Moth counts plotted</a></li>
<li class="chapter" data-level="3.2.3" data-path="GLMMsR.html"><a href="GLMMsR.html#trap-locations"><i class="fa fa-check"></i><b>3.2.3</b> Trap locations</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="GLMMsR.html"><a href="GLMMsR.html#fit-glmR"><i class="fa fa-check"></i><b>3.3</b> Fitted GLM models</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="GLMMsR.html"><a href="GLMMsR.html#frequentist-poisson-model"><i class="fa fa-check"></i><b>3.3.1</b> Frequentist Poisson model</a></li>
<li class="chapter" data-level="3.3.2" data-path="GLMMsR.html"><a href="GLMMsR.html#nb1"><i class="fa fa-check"></i><b>3.3.2</b> Frequentist NB model</a></li>
<li class="chapter" data-level="3.3.3" data-path="GLMMsR.html"><a href="GLMMsR.html#bayesian-model-1"><i class="fa fa-check"></i><b>3.3.3</b> Bayesian model</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="GLMMsR.html"><a href="GLMMsR.html#fit-glmmR"><i class="fa fa-check"></i><b>3.4</b> GLMM: Random effects (RE) for locations</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="GLMMsR.html"><a href="GLMMsR.html#glmm-poisson-fit"><i class="fa fa-check"></i><b>3.4.1</b> GLMM Poisson fit</a></li>
<li class="chapter" data-level="3.4.2" data-path="GLMMsR.html"><a href="GLMMsR.html#glmm-neg-binom-fit"><i class="fa fa-check"></i><b>3.4.2</b> GLMM neg binom fit</a></li>
<li class="chapter" data-level="3.4.3" data-path="GLMMsR.html"><a href="GLMMsR.html#glmm-bayesian-fit"><i class="fa fa-check"></i><b>3.4.3</b> GLMM Bayesian fit</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="GLMMsR.html"><a href="GLMMsR.html#fit-glmm-datesR"><i class="fa fa-check"></i><b>3.5</b> GLMM: RE for location, sampling date</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="GLMMsR.html"><a href="GLMMsR.html#crossed-poisson-glmm-fit"><i class="fa fa-check"></i><b>3.5.1</b> Crossed Poisson GLMM fit</a></li>
<li class="chapter" data-level="3.5.2" data-path="GLMMsR.html"><a href="GLMMsR.html#crossed-nb-glmm-fit"><i class="fa fa-check"></i><b>3.5.2</b> Crossed NB GLMM fit</a></li>
<li class="chapter" data-level="3.5.3" data-path="GLMMsR.html"><a href="GLMMsR.html#crossed-bayes-glmm-fit"><i class="fa fa-check"></i><b>3.5.3</b> Crossed Bayes GLMM fit</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="GLMMsR.html"><a href="GLMMsR.html#fit-glmm-gpR"><i class="fa fa-check"></i><b>3.6</b> GLMM with Gaussian Processes: RE for Trial, GP for Date</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="GLMMsR.html"><a href="GLMMsR.html#gaussian-process-bayes-glmm-fit"><i class="fa fa-check"></i><b>3.6.1</b> Gaussian Process Bayes GLMM fit</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="GLMMsR.html"><a href="GLMMsR.html#summary-of-estimates"><i class="fa fa-check"></i><b>3.7</b> Summary of estimates</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="GLMMsR.html"><a href="GLMMsR.html#compareTR"><i class="fa fa-check"></i><b>3.7.1</b> Compare TR estimates</a></li>
<li class="chapter" data-level="3.7.2" data-path="GLMMsR.html"><a href="GLMMsR.html#compare-coefficients"><i class="fa fa-check"></i><b>3.7.2</b> Compare coefficients</a></li>
<li class="chapter" data-level="3.7.3" data-path="GLMMsR.html"><a href="GLMMsR.html#plot-comparisons"><i class="fa fa-check"></i><b>3.7.3</b> Plot comparisons</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="GLMMsPython.html"><a href="GLMMsPython.html"><i class="fa fa-check"></i><b>4</b> GLMM’s in Python</a>
<ul>
<li class="chapter" data-level="4.1" data-path="GLMMsPython.html"><a href="GLMMsPython.html#getting-started-with-python"><i class="fa fa-check"></i><b>4.1</b> Getting started with Python</a></li>
<li class="chapter" data-level="4.2" data-path="GLMMsPython.html"><a href="GLMMsPython.html#setup-1"><i class="fa fa-check"></i><b>4.2</b> Setup</a></li>
<li class="chapter" data-level="4.3" data-path="GLMMsPython.html"><a href="GLMMsPython.html#data-exploration-1"><i class="fa fa-check"></i><b>4.3</b> Data exploration</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="GLMMsPython.html"><a href="GLMMsPython.html#the-data-1"><i class="fa fa-check"></i><b>4.3.1</b> The data</a></li>
<li class="chapter" data-level="4.3.2" data-path="GLMMsPython.html"><a href="GLMMsPython.html#moth-counts-plotted-1"><i class="fa fa-check"></i><b>4.3.2</b> Moth counts plotted</a></li>
<li class="chapter" data-level="4.3.3" data-path="GLMMsPython.html"><a href="GLMMsPython.html#trap-locations-1"><i class="fa fa-check"></i><b>4.3.3</b> Trap locations</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="GLMMsPython.html"><a href="GLMMsPython.html#fit-glmPy"><i class="fa fa-check"></i><b>4.4</b> Fitted GLM models</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="GLMMsPython.html"><a href="GLMMsPython.html#frequentist-poisson-model-1"><i class="fa fa-check"></i><b>4.4.1</b> Frequentist Poisson model</a></li>
<li class="chapter" data-level="4.4.2" data-path="GLMMsPython.html"><a href="GLMMsPython.html#nb1Py"><i class="fa fa-check"></i><b>4.4.2</b> Frequentist NB model</a></li>
<li class="chapter" data-level="4.4.3" data-path="GLMMsPython.html"><a href="GLMMsPython.html#bayesian-bambi-model"><i class="fa fa-check"></i><b>4.4.3</b> Bayesian (bambi) model</a></li>
<li class="chapter" data-level="4.4.4" data-path="GLMMsPython.html"><a href="GLMMsPython.html#bayesian-pymc-models-python"><i class="fa fa-check"></i><b>4.4.4</b> Bayesian (PyMC) models– Python</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="GLMMsPython.html"><a href="GLMMsPython.html#summary-of-estimates-1"><i class="fa fa-check"></i><b>4.5</b> Summary of estimates</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="GLMMsPython.html"><a href="GLMMsPython.html#compare-tr-estimates"><i class="fa fa-check"></i><b>4.5.1</b> Compare TR estimates</a></li>
<li class="chapter" data-level="4.5.2" data-path="GLMMsPython.html"><a href="GLMMsPython.html#compare-coefficients-1"><i class="fa fa-check"></i><b>4.5.2</b> Compare coefficients</a></li>
<li class="chapter" data-level="4.5.3" data-path="GLMMsPython.html"><a href="GLMMsPython.html#plot-comparisons-1"><i class="fa fa-check"></i><b>4.5.3</b> Plot comparisons</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="NonlinearR.html"><a href="NonlinearR.html"><i class="fa fa-check"></i><b>5</b> Nonlinear Bayesian Models in R</a>
<ul>
<li class="chapter" data-level="5.1" data-path="NonlinearR.html"><a href="NonlinearR.html#setup-2"><i class="fa fa-check"></i><b>5.1</b> Setup</a></li>
<li class="chapter" data-level="5.2" data-path="NonlinearR.html"><a href="NonlinearR.html#generalized-logistic-curve"><i class="fa fa-check"></i><b>5.2</b> Generalized Logistic Curve</a></li>
<li class="chapter" data-level="5.3" data-path="NonlinearR.html"><a href="NonlinearR.html#bayesian-model-2"><i class="fa fa-check"></i><b>5.3</b> Bayesian model</a></li>
<li class="chapter" data-level="5.4" data-path="NonlinearR.html"><a href="NonlinearR.html#fitting-models-with-the-brms-package"><i class="fa fa-check"></i><b>5.4</b> Fitting models with the brms package</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="NonlinearR.html"><a href="NonlinearR.html#no-re-no-gp"><i class="fa fa-check"></i><b>5.4.1</b> No RE, no GP</a></li>
<li class="chapter" data-level="5.4.2" data-path="NonlinearR.html"><a href="NonlinearR.html#intercept-re-no-gp"><i class="fa fa-check"></i><b>5.4.2</b> Intercept RE, no GP</a></li>
<li class="chapter" data-level="5.4.3" data-path="NonlinearR.html"><a href="NonlinearR.html#intercept-re-a-re-no-gp"><i class="fa fa-check"></i><b>5.4.3</b> Intercept RE, A RE, no GP</a></li>
<li class="chapter" data-level="5.4.4" data-path="NonlinearR.html"><a href="NonlinearR.html#intercept-re-a-re-with-gp-same-for-all-loc"><i class="fa fa-check"></i><b>5.4.4</b> Intercept RE, A RE, WITH GP (same for all loc)</a></li>
<li class="chapter" data-level="5.4.5" data-path="NonlinearR.html"><a href="NonlinearR.html#intercept-a-re-with-gp-diff-for-each-loc"><i class="fa fa-check"></i><b>5.4.5</b> Intercept, A RE, with GP (DIFF for each loc)</a></li>
<li class="chapter" data-level="5.4.6" data-path="NonlinearR.html"><a href="NonlinearR.html#intercept-a-b-m-re-with-gp-diff-for-each-loc"><i class="fa fa-check"></i><b>5.4.6</b> Intercept, A, B, M RE, with GP (DIFF for each loc)</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="NonlinearR.html"><a href="NonlinearR.html#case-study"><i class="fa fa-check"></i><b>5.5</b> Case study</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Bayesian models in R and Python</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="GLMMsPython" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> GLMM’s in Python<a href="GLMMsPython.html#GLMMsPython" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="getting-started-with-python" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Getting started with Python<a href="GLMMsPython.html#getting-started-with-python" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Python is a lot more complicated than R!</p>
<ol style="list-style-type: decimal">
<li><p>Download Python.</p></li>
<li><p>Decide how you want to interact with Python. Yes, you can technically use the terminal and use Python directly, but a GUI is preferable so that it is easier to run the code, add comments, view the output, etc. This is even more true for Python than it is for R.</p></li>
</ol>
<p>Originally, I downloaded Jupyter Notebook directly, but I didn’t like the way things loaded. So, I downloaded “Anaconda” and then accessed Jupyter from there. However, I still don’t love Jupyter– the notebooks don’t optimize the screen’s size like RStudio does. In RStudio, I love having my code on one side of the screen, and my outputs on the other. Screens are wide, not long.</p>
<p>Soon, I came across the “reticulate” package, which allows for Python coding in an Rmarkdown script! So far, awesome and it is how I run the all the analyses. Here, I switch between R and Python code chunks, but the package also allows objects written in one language to be used within both languages. Pretty cool. It’s not for production-level code, but seems perfect for R users switching to Python.</p>
<p>To interact with Python via RMarkdowns in RStudio, check out the <code>reticulate</code> package <a href="https://rstudio.github.io/reticulate/articles/r_markdown.html">website</a>.</p>
<p>Here is another helpful link: <a href="https://rstudio.github.io/reticulate/articles/python_primer.html">Primer on Python for R users</a></p>
<ol start="3" style="list-style-type: decimal">
<li>Set up a Python environment for your work. (Second code chunk in the setup.) Here is why that is important:</li>
</ol>
<p>Python environments:
“When installing Python packages it’s best practice to isolate them within a Python environment (a named Python installation that exists for a specific project or purpose). This provides a measure of isolation, so that updating a Python package for one project doesn’t impact other projects. The risk for package incompatibilities is significantly higher with Python packages than it is with R packages, because unlike CRAN, PyPI does not enforce, or even check, if the current versions of packages currently available are compatible.”
<a href="https://rstudio.github.io/reticulate/articles/python_packages.html" class="uri">https://rstudio.github.io/reticulate/articles/python_packages.html</a></p>
<p>Anaconda and reticulate both help the user keep specific environments for each Python “project” that one may be working on.</p>
<p>A Python virtual environment is a basic tool to isolate project dependencies within a Python installation, while a Conda environment is a more comprehensive package manager that not only creates isolated environments but also allows for managing complex dependencies across different programming languages. To keep things simpler, I use a Python virtual environment.</p>
<ol start="4" style="list-style-type: decimal">
<li>Install Python modules as needed.</li>
</ol>
<p>Python libraries or packages are called <strong>modules</strong>. To use them with <code>reticulate</code>, you first have to import them (third code chunk). The lines in the third code chunk below must be called exactly once each for each new python module used; it does not need to re-run.</p>
</div>
<div id="setup-1" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Setup<a href="GLMMsPython.html#setup-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As in the R chapters, all modules (i.e., packages) are loaded and the data are uploaded and mainpulated at the start of the script. The “Getting started with Python” section above goes into details on the rhyme and reason for some of these code chunks.</p>
<p>Because I am newer to Python, the required modules are often included in the code chunks as well as a reminder of what modules are used for what functions. They are included in the setup to ensure that there are no issues upon loading.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="GLMMsPython.html#cb53-1" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">cache =</span> F, <span class="at">message =</span> F, <span class="at">warning =</span> F, </span>
<span id="cb53-2"><a href="GLMMsPython.html#cb53-2" tabindex="-1"></a>  <span class="at">out.width =</span> <span class="st">&#39;100%&#39;</span>)</span>
<span id="cb53-3"><a href="GLMMsPython.html#cb53-3" tabindex="-1"></a><span class="fu">library</span>(kableExtra) <span class="co"># to make a pretty table</span></span>
<span id="cb53-4"><a href="GLMMsPython.html#cb53-4" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co"># %&gt;% function, and others</span></span>
<span id="cb53-5"><a href="GLMMsPython.html#cb53-5" tabindex="-1"></a><span class="fu">library</span>(reticulate) <span class="co"># library to use Python within R</span></span>
<span id="cb53-6"><a href="GLMMsPython.html#cb53-6" tabindex="-1"></a><span class="fu">use_virtualenv</span>(<span class="st">&quot;r-reticulate-BayesInPython&quot;</span>)</span>
<span id="cb53-7"><a href="GLMMsPython.html#cb53-7" tabindex="-1"></a></span>
<span id="cb53-8"><a href="GLMMsPython.html#cb53-8" tabindex="-1"></a><span class="co"># make sure these packages are installed before installing pymer4:</span></span>
<span id="cb53-9"><a href="GLMMsPython.html#cb53-9" tabindex="-1"></a><span class="co"># install.packages(c(&quot;lme4&quot;, &quot;lmerTest&quot;, &quot;emmeans&quot;))</span></span>
<span id="cb53-10"><a href="GLMMsPython.html#cb53-10" tabindex="-1"></a><span class="co"># Ensure pymer4 is installed in the desired Python environment</span></span>
<span id="cb53-11"><a href="GLMMsPython.html#cb53-11" tabindex="-1"></a><span class="co"># py_require(&quot;pymer4&quot;)</span></span></code></pre></div>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="GLMMsPython.html#cb54-1" tabindex="-1"></a><span class="do">## Uncomment the code below and run once, the first time you work through the tutorial:</span></span>
<span id="cb54-2"><a href="GLMMsPython.html#cb54-2" tabindex="-1"></a></span>
<span id="cb54-3"><a href="GLMMsPython.html#cb54-3" tabindex="-1"></a><span class="co"># create a new environment</span></span>
<span id="cb54-4"><a href="GLMMsPython.html#cb54-4" tabindex="-1"></a><span class="co"># virtualenv_create(&quot;r-reticulate-BayesInPython&quot;)</span></span>
<span id="cb54-5"><a href="GLMMsPython.html#cb54-5" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb54-6"><a href="GLMMsPython.html#cb54-6" tabindex="-1"></a><span class="co"># # install a module</span></span>
<span id="cb54-7"><a href="GLMMsPython.html#cb54-7" tabindex="-1"></a><span class="co"># virtualenv_install(&quot;r-reticulate-BayesInPython&quot;, &quot;pandas&quot;)</span></span>
<span id="cb54-8"><a href="GLMMsPython.html#cb54-8" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb54-9"><a href="GLMMsPython.html#cb54-9" tabindex="-1"></a><span class="co"># indicate that we want to use a specific virtualenv</span></span>
<span id="cb54-10"><a href="GLMMsPython.html#cb54-10" tabindex="-1"></a><span class="co"># use_virtualenv(&quot;r-reticulate-BayesInPython&quot;)</span></span>
<span id="cb54-11"><a href="GLMMsPython.html#cb54-11" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb54-12"><a href="GLMMsPython.html#cb54-12" tabindex="-1"></a></span>
<span id="cb54-13"><a href="GLMMsPython.html#cb54-13" tabindex="-1"></a><span class="do">## (Uncomment this code instead if you prefer a Conda environment) </span></span>
<span id="cb54-14"><a href="GLMMsPython.html#cb54-14" tabindex="-1"></a><span class="co"># # create a new environment </span></span>
<span id="cb54-15"><a href="GLMMsPython.html#cb54-15" tabindex="-1"></a><span class="co"># conda_create(&quot;r-reticulate-BayesInPython&quot;)</span></span>
<span id="cb54-16"><a href="GLMMsPython.html#cb54-16" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb54-17"><a href="GLMMsPython.html#cb54-17" tabindex="-1"></a><span class="co"># # install a module, e.g., SciPy</span></span>
<span id="cb54-18"><a href="GLMMsPython.html#cb54-18" tabindex="-1"></a><span class="co"># conda_install(&quot;r-reticulate-BayesInPython&quot;, &quot;scipy&quot;)</span></span>
<span id="cb54-19"><a href="GLMMsPython.html#cb54-19" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb54-20"><a href="GLMMsPython.html#cb54-20" tabindex="-1"></a><span class="co"># # indicate that we want to use a specific condaenv</span></span>
<span id="cb54-21"><a href="GLMMsPython.html#cb54-21" tabindex="-1"></a><span class="co"># use_condaenv(&quot;r-reticulate-BayesInPython&quot;)</span></span></code></pre></div>
<div class="sourceCode" id="cb55"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb55-1"><a href="GLMMsPython.html#cb55-1" tabindex="-1"></a><span class="co">## Install modules if you have not used them before</span></span>
<span id="cb55-2"><a href="GLMMsPython.html#cb55-2" tabindex="-1"></a><span class="co"># You may have to install the packages if you have not used them before:</span></span>
<span id="cb55-3"><a href="GLMMsPython.html#cb55-3" tabindex="-1"></a><span class="co"># code chunk is here for easy retrieval</span></span>
<span id="cb55-4"><a href="GLMMsPython.html#cb55-4" tabindex="-1"></a><span class="co"># replace module name as needed.</span></span>
<span id="cb55-5"><a href="GLMMsPython.html#cb55-5" tabindex="-1"></a><span class="op">!</span>pip install staticmap</span>
<span id="cb55-6"><a href="GLMMsPython.html#cb55-6" tabindex="-1"></a></span>
<span id="cb55-7"><a href="GLMMsPython.html#cb55-7" tabindex="-1"></a><span class="co"># installing googlemaps needs a modification:</span></span>
<span id="cb55-8"><a href="GLMMsPython.html#cb55-8" tabindex="-1"></a><span class="co"># !pip install  --use-pep517 googlemaps</span></span>
<span id="cb55-9"><a href="GLMMsPython.html#cb55-9" tabindex="-1"></a></span>
<span id="cb55-10"><a href="GLMMsPython.html#cb55-10" tabindex="-1"></a><span class="co"># to install pymer4, you need to type the following commands from Terminal:</span></span>
<span id="cb55-11"><a href="GLMMsPython.html#cb55-11" tabindex="-1"></a><span class="co"># I think you need Anaconda installed</span></span>
<span id="cb55-12"><a href="GLMMsPython.html#cb55-12" tabindex="-1"></a><span class="co">## https://eshinjolly.com/pymer4/installation.html</span></span>
<span id="cb55-13"><a href="GLMMsPython.html#cb55-13" tabindex="-1"></a><span class="co"># conda create --name pymer4 -c ejolly -c conda-forge -c defaults pymer4</span></span>
<span id="cb55-14"><a href="GLMMsPython.html#cb55-14" tabindex="-1"></a><span class="co"># conda activate pymer4</span></span></code></pre></div>
<div class="sourceCode" id="cb56"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb56-1"><a href="GLMMsPython.html#cb56-1" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb56-2"><a href="GLMMsPython.html#cb56-2" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb56-3"><a href="GLMMsPython.html#cb56-3" tabindex="-1"></a></span>
<span id="cb56-4"><a href="GLMMsPython.html#cb56-4" tabindex="-1"></a><span class="im">import</span> pprint</span>
<span id="cb56-5"><a href="GLMMsPython.html#cb56-5" tabindex="-1"></a><span class="im">from</span> staticmap <span class="im">import</span> StaticMap, CircleMarker <span class="co"># plot trap locations on a map</span></span>
<span id="cb56-6"><a href="GLMMsPython.html#cb56-6" tabindex="-1"></a><span class="im">import</span> arviz <span class="im">as</span> az</span>
<span id="cb56-7"><a href="GLMMsPython.html#cb56-7" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt </span>
<span id="cb56-8"><a href="GLMMsPython.html#cb56-8" tabindex="-1"></a><span class="im">from</span> formulae <span class="im">import</span> design_matrices</span>
<span id="cb56-9"><a href="GLMMsPython.html#cb56-9" tabindex="-1"></a></span>
<span id="cb56-10"><a href="GLMMsPython.html#cb56-10" tabindex="-1"></a><span class="im">import</span> patsy <span class="co"># for dmatrix function</span></span>
<span id="cb56-11"><a href="GLMMsPython.html#cb56-11" tabindex="-1"></a></span>
<span id="cb56-12"><a href="GLMMsPython.html#cb56-12" tabindex="-1"></a><span class="im">from</span> plotnine <span class="im">import</span> <span class="op">*</span> <span class="co"># using ggplot in Python</span></span>
<span id="cb56-13"><a href="GLMMsPython.html#cb56-13" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns </span>
<span id="cb56-14"><a href="GLMMsPython.html#cb56-14" tabindex="-1"></a></span>
<span id="cb56-15"><a href="GLMMsPython.html#cb56-15" tabindex="-1"></a><span class="im">import</span> os <span class="co"># save API key in .env file</span></span>
<span id="cb56-16"><a href="GLMMsPython.html#cb56-16" tabindex="-1"></a><span class="im">import</span> gmplot <span class="co">## ggmap </span></span>
<span id="cb56-17"><a href="GLMMsPython.html#cb56-17" tabindex="-1"></a></span>
<span id="cb56-18"><a href="GLMMsPython.html#cb56-18" tabindex="-1"></a><span class="im">from</span> patsy <span class="im">import</span> dmatrices <span class="co"># for dmatrices function</span></span>
<span id="cb56-19"><a href="GLMMsPython.html#cb56-19" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm <span class="co"># for regressions</span></span>
<span id="cb56-20"><a href="GLMMsPython.html#cb56-20" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb56-21"><a href="GLMMsPython.html#cb56-21" tabindex="-1"></a></span>
<span id="cb56-22"><a href="GLMMsPython.html#cb56-22" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> nbinom</span>
<span id="cb56-23"><a href="GLMMsPython.html#cb56-23" tabindex="-1"></a></span>
<span id="cb56-24"><a href="GLMMsPython.html#cb56-24" tabindex="-1"></a><span class="im">import</span> bambi <span class="im">as</span> bmb</span>
<span id="cb56-25"><a href="GLMMsPython.html#cb56-25" tabindex="-1"></a><span class="im">import</span> pymc <span class="im">as</span> pm</span>
<span id="cb56-26"><a href="GLMMsPython.html#cb56-26" tabindex="-1"></a></span>
<span id="cb56-27"><a href="GLMMsPython.html#cb56-27" tabindex="-1"></a><span class="im">import</span> pickle <span class="co"># to write, read python objects to file</span></span>
<span id="cb56-28"><a href="GLMMsPython.html#cb56-28" tabindex="-1"></a></span>
<span id="cb56-29"><a href="GLMMsPython.html#cb56-29" tabindex="-1"></a></span>
<span id="cb56-30"><a href="GLMMsPython.html#cb56-30" tabindex="-1"></a>mycolors <span class="op">=</span> [<span class="st">&quot;#9E0142&quot;</span>, <span class="st">&quot;#66C2A5&quot;</span>]</span></code></pre></div>
<div class="sourceCode" id="cb57"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb57-1"><a href="GLMMsPython.html#cb57-1" tabindex="-1"></a><span class="co">## Define some functions to use in this script.</span></span>
<span id="cb57-2"><a href="GLMMsPython.html#cb57-2" tabindex="-1"></a></span>
<span id="cb57-3"><a href="GLMMsPython.html#cb57-3" tabindex="-1"></a><span class="co"># calculate trapping reduction for frequentist model fits.</span></span>
<span id="cb57-4"><a href="GLMMsPython.html#cb57-4" tabindex="-1"></a><span class="kw">def</span> getTR(mod):</span>
<span id="cb57-5"><a href="GLMMsPython.html#cb57-5" tabindex="-1"></a>    <span class="co">&quot;&quot;&quot;Calculate TR with confidence interval for stats model&quot;&quot;&quot;</span></span>
<span id="cb57-6"><a href="GLMMsPython.html#cb57-6" tabindex="-1"></a>    <span class="co"># Function body</span></span>
<span id="cb57-7"><a href="GLMMsPython.html#cb57-7" tabindex="-1"></a>    <span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb57-8"><a href="GLMMsPython.html#cb57-8" tabindex="-1"></a></span>
<span id="cb57-9"><a href="GLMMsPython.html#cb57-9" tabindex="-1"></a>    b1 <span class="op">=</span> mod.params.iloc[<span class="dv">1</span>]</span>
<span id="cb57-10"><a href="GLMMsPython.html#cb57-10" tabindex="-1"></a>    seb1 <span class="op">=</span> mod.bse.iloc[<span class="dv">1</span>]</span>
<span id="cb57-11"><a href="GLMMsPython.html#cb57-11" tabindex="-1"></a>    </span>
<span id="cb57-12"><a href="GLMMsPython.html#cb57-12" tabindex="-1"></a>    outTR <span class="op">=</span> {<span class="st">&#39;TR&#39;</span>: [<span class="bu">round</span>(<span class="dv">100</span> <span class="op">*</span> <span class="dv">1</span> <span class="op">-</span> math.exp(b1))], </span>
<span id="cb57-13"><a href="GLMMsPython.html#cb57-13" tabindex="-1"></a>    <span class="st">&#39;lowerCI&#39;</span>: [<span class="bu">round</span>(<span class="dv">100</span> <span class="op">*</span> <span class="dv">1</span> <span class="op">-</span> math.exp(b1 <span class="op">+</span> <span class="fl">1.96</span><span class="op">*</span>seb1))],</span>
<span id="cb57-14"><a href="GLMMsPython.html#cb57-14" tabindex="-1"></a>    <span class="st">&#39;upperCI&#39;</span>: [<span class="bu">round</span>(<span class="dv">100</span> <span class="op">*</span> <span class="dv">1</span> <span class="op">-</span> math.exp(b1 <span class="op">-</span> <span class="fl">1.96</span><span class="op">*</span>seb1))]}</span>
<span id="cb57-15"><a href="GLMMsPython.html#cb57-15" tabindex="-1"></a>    df <span class="op">=</span> pd.DataFrame(outTR)</span>
<span id="cb57-16"><a href="GLMMsPython.html#cb57-16" tabindex="-1"></a>    <span class="cf">return</span> df</span></code></pre></div>
<div class="sourceCode" id="cb58"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb58-1"><a href="GLMMsPython.html#cb58-1" tabindex="-1"></a><span class="co">## Read in the moth data:</span></span>
<span id="cb58-2"><a href="GLMMsPython.html#cb58-2" tabindex="-1"></a></span>
<span id="cb58-3"><a href="GLMMsPython.html#cb58-3" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb58-4"><a href="GLMMsPython.html#cb58-4" tabindex="-1"></a></span>
<span id="cb58-5"><a href="GLMMsPython.html#cb58-5" tabindex="-1"></a>datP <span class="op">=</span> pd.read_csv(<span class="st">&quot;data/moths.csv&quot;</span>, delimiter <span class="op">=</span> <span class="st">&quot;,&quot;</span>)</span>
<span id="cb58-6"><a href="GLMMsPython.html#cb58-6" tabindex="-1"></a></span>
<span id="cb58-7"><a href="GLMMsPython.html#cb58-7" tabindex="-1"></a><span class="co"># check data values: </span></span>
<span id="cb58-8"><a href="GLMMsPython.html#cb58-8" tabindex="-1"></a><span class="co"># (Results not shown for succinctness)</span></span>
<span id="cb58-9"><a href="GLMMsPython.html#cb58-9" tabindex="-1"></a>datP.info()</span></code></pre></div>
<div class="sourceCode" id="cb59"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb59-1"><a href="GLMMsPython.html#cb59-1" tabindex="-1"></a>pd.set_option(<span class="st">&#39;display.max_columns&#39;</span>, <span class="va">None</span>) <span class="co"># Display all columns</span></span>
<span id="cb59-2"><a href="GLMMsPython.html#cb59-2" tabindex="-1"></a>datP.describe(percentiles<span class="op">=</span>[<span class="fl">0.5</span>], include <span class="op">=</span> <span class="st">&#39;all&#39;</span>)</span>
<span id="cb59-3"><a href="GLMMsPython.html#cb59-3" tabindex="-1"></a></span>
<span id="cb59-4"><a href="GLMMsPython.html#cb59-4" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> datP:</span>
<span id="cb59-5"><a href="GLMMsPython.html#cb59-5" tabindex="-1"></a>  <span class="cf">if</span> (datP[col].dtype <span class="op">==</span> <span class="st">&#39;object&#39;</span>):</span>
<span id="cb59-6"><a href="GLMMsPython.html#cb59-6" tabindex="-1"></a>    <span class="bu">print</span>(col)</span>
<span id="cb59-7"><a href="GLMMsPython.html#cb59-7" tabindex="-1"></a>    <span class="bu">print</span>(datP[col].unique())</span></code></pre></div>
<div class="sourceCode" id="cb60"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb60-1"><a href="GLMMsPython.html#cb60-1" tabindex="-1"></a><span class="co">## manipulate data as needed:</span></span>
<span id="cb60-2"><a href="GLMMsPython.html#cb60-2" tabindex="-1"></a></span>
<span id="cb60-3"><a href="GLMMsPython.html#cb60-3" tabindex="-1"></a><span class="co"># convert dates to dates in case further manipulation on them is needed:</span></span>
<span id="cb60-4"><a href="GLMMsPython.html#cb60-4" tabindex="-1"></a><span class="co"># but first keep object version of samplingdate:</span></span>
<span id="cb60-5"><a href="GLMMsPython.html#cb60-5" tabindex="-1"></a>datP[<span class="st">&#39;SamplingDateC&#39;</span>] <span class="op">=</span> datP[<span class="st">&#39;SamplingDate&#39;</span>]</span>
<span id="cb60-6"><a href="GLMMsPython.html#cb60-6" tabindex="-1"></a>cols <span class="op">=</span> [<span class="st">&#39;TransplantDate&#39;</span>, <span class="st">&#39;DispInstallDate&#39;</span>, <span class="st">&#39;TrapInstallDate&#39;</span>, <span class="st">&#39;SamplingDate&#39;</span>]</span>
<span id="cb60-7"><a href="GLMMsPython.html#cb60-7" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> cols:</span>
<span id="cb60-8"><a href="GLMMsPython.html#cb60-8" tabindex="-1"></a>    datP[col] <span class="op">=</span> pd.to_datetime(datP[col])</span>
<span id="cb60-9"><a href="GLMMsPython.html#cb60-9" tabindex="-1"></a>datP[<span class="st">&#39;SamplingDate&#39;</span>].describe()</span></code></pre></div>
<div class="sourceCode" id="cb61"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb61-1"><a href="GLMMsPython.html#cb61-1" tabindex="-1"></a><span class="co"># standardize the counts</span></span>
<span id="cb61-2"><a href="GLMMsPython.html#cb61-2" tabindex="-1"></a>datP[<span class="st">&#39;mothsperday&#39;</span>] <span class="op">=</span> datP[<span class="st">&#39;nYSB&#39;</span>] <span class="op">/</span> datP[<span class="st">&#39;DaysOfCatch&#39;</span>]</span>
<span id="cb61-3"><a href="GLMMsPython.html#cb61-3" tabindex="-1"></a></span>
<span id="cb61-4"><a href="GLMMsPython.html#cb61-4" tabindex="-1"></a><span class="co"># un-comment if we need to fix levels in non-alpha order</span></span>
<span id="cb61-5"><a href="GLMMsPython.html#cb61-5" tabindex="-1"></a><span class="co"># datR &lt;- datP %&gt;%</span></span>
<span id="cb61-6"><a href="GLMMsPython.html#cb61-6" tabindex="-1"></a><span class="co">#   mutate(TreatmentF = factor(Treatment), </span></span>
<span id="cb61-7"><a href="GLMMsPython.html#cb61-7" tabindex="-1"></a>         <span class="co"># LocationF = as.factor(Location),</span></span>
<span id="cb61-8"><a href="GLMMsPython.html#cb61-8" tabindex="-1"></a></span>
<span id="cb61-9"><a href="GLMMsPython.html#cb61-9" tabindex="-1"></a></span>
<span id="cb61-10"><a href="GLMMsPython.html#cb61-10" tabindex="-1"></a><span class="co">## average counts for each location, date</span></span>
<span id="cb61-11"><a href="GLMMsPython.html#cb61-11" tabindex="-1"></a>mean_cts <span class="op">=</span> datP.groupby([<span class="st">&#39;Location&#39;</span>, <span class="st">&#39;Treatment&#39;</span>, <span class="st">&#39;AssessmentNumber&#39;</span>, <span class="st">&#39;SamplingDate&#39;</span>, <span class="st">&#39;SamplingDateC&#39;</span>, <span class="st">&#39;DATI&#39;</span>], as_index<span class="op">=</span><span class="va">False</span>).agg({<span class="st">&#39;nYSB&#39;</span>: <span class="st">&#39;mean&#39;</span>, <span class="st">&#39;mothsperday&#39;</span>: <span class="st">&#39;mean&#39;</span>})</span>
<span id="cb61-12"><a href="GLMMsPython.html#cb61-12" tabindex="-1"></a>mean_cts.describe(include<span class="op">=</span><span class="st">&#39;all&#39;</span>)</span></code></pre></div>
</div>
<div id="data-exploration-1" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Data exploration<a href="GLMMsPython.html#data-exploration-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="the-data-1" class="section level3 hasAnchor" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> The data<a href="GLMMsPython.html#the-data-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Here is what the data look like after the above manipulation.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb62-1"><a href="GLMMsPython.html#cb62-1" tabindex="-1"></a><span class="co"># kable(head(datR, 5)) %&gt;%</span></span>
<span id="cb62-2"><a href="GLMMsPython.html#cb62-2" tabindex="-1"></a><span class="co">#   kable_styling() %&gt;%</span></span>
<span id="cb62-3"><a href="GLMMsPython.html#cb62-3" tabindex="-1"></a><span class="co">#   scroll_box(width = &quot;100%&quot;, box_css = &quot;border: 0px;&quot;)</span></span>
<span id="cb62-4"><a href="GLMMsPython.html#cb62-4" tabindex="-1"></a><span class="co"># convert to DF to make a pretty table:</span></span>
<span id="cb62-5"><a href="GLMMsPython.html#cb62-5" tabindex="-1"></a>py_df <span class="op">=</span> pd.DataFrame(datP)</span>
<span id="cb62-6"><a href="GLMMsPython.html#cb62-6" tabindex="-1"></a><span class="co"># print(datP.head(5))</span></span></code></pre></div>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="GLMMsPython.html#cb63-1" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(py<span class="sc">$</span>datP, <span class="dv">5</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb63-2"><a href="GLMMsPython.html#cb63-2" tabindex="-1"></a>  <span class="fu">kable_styling</span>() <span class="sc">%&gt;%</span></span>
<span id="cb63-3"><a href="GLMMsPython.html#cb63-3" tabindex="-1"></a>  <span class="fu">scroll_box</span>(<span class="at">width =</span> <span class="st">&quot;100%&quot;</span>, <span class="at">box_css =</span> <span class="st">&quot;border: 0px;&quot;</span>)</span></code></pre></div>
<div style="border: 0px;overflow-x: scroll; width:100%; ">
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Location
</th>
<th style="text-align:left;">
Treatment
</th>
<th style="text-align:right;">
TrapID
</th>
<th style="text-align:right;">
Longitude
</th>
<th style="text-align:right;">
Latitude
</th>
<th style="text-align:left;">
TransplantDate
</th>
<th style="text-align:left;">
TrapInstallDate
</th>
<th style="text-align:left;">
DispInstallDate
</th>
<th style="text-align:right;">
AssessmentNumber
</th>
<th style="text-align:left;">
SamplingDate
</th>
<th style="text-align:right;">
nYSB
</th>
<th style="text-align:right;">
DaysOfCatch
</th>
<th style="text-align:right;">
DATI
</th>
<th style="text-align:right;">
DADI
</th>
<th style="text-align:right;">
DAT
</th>
<th style="text-align:left;">
SamplingDateC
</th>
<th style="text-align:right;">
mothsperday
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Loc9
</td>
<td style="text-align:left;">
Trt
</td>
<td style="text-align:right;">
201
</td>
<td style="text-align:right;">
111.6028
</td>
<td style="text-align:right;">
-7.233634
</td>
<td style="text-align:left;">
2023-08-05 18:00:00
</td>
<td style="text-align:left;">
2023-08-12 18:00:00
</td>
<td style="text-align:left;">
2023-08-12 18:00:00
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
2023-08-22 18:00:00
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:left;">
2023-08-23
</td>
<td style="text-align:right;">
0.4000000
</td>
</tr>
<tr>
<td style="text-align:left;">
Loc9
</td>
<td style="text-align:left;">
Trt
</td>
<td style="text-align:right;">
201
</td>
<td style="text-align:right;">
111.6028
</td>
<td style="text-align:right;">
-7.233634
</td>
<td style="text-align:left;">
2023-08-05 18:00:00
</td>
<td style="text-align:left;">
2023-08-12 18:00:00
</td>
<td style="text-align:left;">
2023-08-12 18:00:00
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
2023-09-02 18:00:00
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
28
</td>
<td style="text-align:left;">
2023-09-03
</td>
<td style="text-align:right;">
0.5454545
</td>
</tr>
<tr>
<td style="text-align:left;">
Loc9
</td>
<td style="text-align:left;">
Trt
</td>
<td style="text-align:right;">
201
</td>
<td style="text-align:right;">
111.6028
</td>
<td style="text-align:right;">
-7.233634
</td>
<td style="text-align:left;">
2023-08-05 18:00:00
</td>
<td style="text-align:left;">
2023-08-12 18:00:00
</td>
<td style="text-align:left;">
2023-08-12 18:00:00
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
2023-09-11 18:00:00
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:left;">
2023-09-12
</td>
<td style="text-align:right;">
0.6666667
</td>
</tr>
<tr>
<td style="text-align:left;">
Loc9
</td>
<td style="text-align:left;">
Trt
</td>
<td style="text-align:right;">
201
</td>
<td style="text-align:right;">
111.6028
</td>
<td style="text-align:right;">
-7.233634
</td>
<td style="text-align:left;">
2023-08-05 18:00:00
</td>
<td style="text-align:left;">
2023-08-12 18:00:00
</td>
<td style="text-align:left;">
2023-08-12 18:00:00
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
2023-09-22 18:00:00
</td>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
41
</td>
<td style="text-align:right;">
41
</td>
<td style="text-align:right;">
48
</td>
<td style="text-align:left;">
2023-09-23
</td>
<td style="text-align:right;">
2.1818182
</td>
</tr>
<tr>
<td style="text-align:left;">
Loc9
</td>
<td style="text-align:left;">
Trt
</td>
<td style="text-align:right;">
201
</td>
<td style="text-align:right;">
111.6028
</td>
<td style="text-align:right;">
-7.233634
</td>
<td style="text-align:left;">
2023-08-05 18:00:00
</td>
<td style="text-align:left;">
2023-08-12 18:00:00
</td>
<td style="text-align:left;">
2023-08-12 18:00:00
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
2023-10-01 18:00:00
</td>
<td style="text-align:right;">
43
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
50
</td>
<td style="text-align:right;">
50
</td>
<td style="text-align:right;">
57
</td>
<td style="text-align:left;">
2023-10-02
</td>
<td style="text-align:right;">
4.7777778
</td>
</tr>
</tbody>
</table>
</div>
<p>Column descriptions:</p>
<ul>
<li><p><strong>Location</strong>– data were collected from 10 trial locations,</p></li>
<li><p><strong>Treatment</strong>– Control or Treatment (Trt),</p></li>
<li><p><strong>TrapID</strong>– each trap within a trial location has a unique ID,</p></li>
<li><p><strong>Longitude</strong>, <strong>Latitude</strong>– the coordinates of each unique trap,</p></li>
<li><p><strong>TransplantDate</strong>– the date that the rice seedlings were transplanted into the field,</p></li>
<li><p><strong>TrapInstallDate</strong>– the trap installation date, which is usually the same as the dispenser installation date,</p></li>
<li><p><strong>DispInstallDate</strong>– the treatment (pheromone dispenser) installation date;</p></li>
<li><p><strong>AssessmentNumber</strong>– traps are sampled 10 times each. Using assessment number is a way to standardize the sampling dates across locations,</p></li>
<li><p><strong>SamplingDate</strong>– the date on which the trap was checked and moths were counted,</p></li>
<li><p><strong>nYSB</strong>– the moth counts (number of YSB moths) associated with each trap, location, and date,</p></li>
<li><p><strong>DaysOfCatch</strong>– the number of days since the trap was previously sampled or the number of days since trap installation if it is assessment number 1,</p></li>
<li><p><strong>DATI</strong> is days after trap installation;</p></li>
<li><p><strong>DADI</strong>– days after dispenser installation; and</p></li>
<li><p><strong>DAT</strong>– days after transplant.</p></li>
<li><p><strong>mothsperday</strong>– moths caught per day, nYSB / DaysOfCatch, and</p></li>
<li><p><strong>SamplingDateC</strong>– Sampling Date as a character/string (for model in Section \<span class="citation">(<a href="#ref-ref"><strong>ref?</strong></a>)</span>(glmm_datesC)),</p></li>
</ul>
</div>
<div id="moth-counts-plotted-1" class="section level3 hasAnchor" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> Moth counts plotted<a href="GLMMsPython.html#moth-counts-plotted-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The data are the moth counts collected at each trap (average per day), within each location and throughout the season. Note how the y-axis changes for each plot in the figure.</p>
<p>The <code>plotnine</code> module allows us to use <code>ggplot2</code> package in Python. It is fantastic to quickly make a beautiful plot using previously acquired R skills, and it does so with a fraction of the code required to make a similar figure using Python’s <code>seaborn</code> and/or <code>matplotlib</code> modules.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb64-1"><a href="GLMMsPython.html#cb64-1" tabindex="-1"></a><span class="im">from</span> plotnine <span class="im">import</span> <span class="op">*</span> <span class="co"># using ggplot in Python</span></span>
<span id="cb64-2"><a href="GLMMsPython.html#cb64-2" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt </span>
<span id="cb64-3"><a href="GLMMsPython.html#cb64-3" tabindex="-1"></a></span>
<span id="cb64-4"><a href="GLMMsPython.html#cb64-4" tabindex="-1"></a>pmoths <span class="op">=</span> (ggplot(datP, aes(x <span class="op">=</span> <span class="st">&#39;DATI&#39;</span>, y<span class="op">=</span><span class="st">&#39;mothsperday&#39;</span>, color <span class="op">=</span> <span class="st">&#39;Treatment&#39;</span>)) <span class="op">+</span></span>
<span id="cb64-5"><a href="GLMMsPython.html#cb64-5" tabindex="-1"></a>        geom_jitter(height <span class="op">=</span> <span class="dv">0</span>, width <span class="op">=</span> <span class="fl">0.75</span>, alpha <span class="op">=</span> <span class="fl">0.5</span>) <span class="op">+</span></span>
<span id="cb64-6"><a href="GLMMsPython.html#cb64-6" tabindex="-1"></a>        geom_smooth(se<span class="op">=</span><span class="va">False</span>) <span class="op">+</span></span>
<span id="cb64-7"><a href="GLMMsPython.html#cb64-7" tabindex="-1"></a>        facet_wrap([<span class="st">&#39;Location&#39;</span>], scales <span class="op">=</span> <span class="st">&quot;free_y&quot;</span>) <span class="op">+</span></span>
<span id="cb64-8"><a href="GLMMsPython.html#cb64-8" tabindex="-1"></a>        scale_color_manual(values <span class="op">=</span> mycolors) <span class="op">+</span></span>
<span id="cb64-9"><a href="GLMMsPython.html#cb64-9" tabindex="-1"></a>        labs(title <span class="op">=</span> <span class="st">&quot;Male YSB moth counts for each location and trap&quot;</span>,</span>
<span id="cb64-10"><a href="GLMMsPython.html#cb64-10" tabindex="-1"></a>             subtitle <span class="op">=</span> <span class="st">&quot;with smoothing lines&quot;</span>,</span>
<span id="cb64-11"><a href="GLMMsPython.html#cb64-11" tabindex="-1"></a>             y <span class="op">=</span> <span class="st">&quot;Moth counts per trap per day&quot;</span>,</span>
<span id="cb64-12"><a href="GLMMsPython.html#cb64-12" tabindex="-1"></a>             x <span class="op">=</span> <span class="st">&quot;Days after installation (DAI)&quot;</span>,</span>
<span id="cb64-13"><a href="GLMMsPython.html#cb64-13" tabindex="-1"></a>             color <span class="op">=</span> <span class="st">&quot;Treatment&quot;</span>))</span>
<span id="cb64-14"><a href="GLMMsPython.html#cb64-14" tabindex="-1"></a>pmoths.draw(<span class="va">True</span>)</span></code></pre></div>
<p><img src="03-GLMMsInPython_files/figure-html/plotMothsPy-1.png" width="100%" /></p>
<div class="sourceCode" id="cb65"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb65-1"><a href="GLMMsPython.html#cb65-1" tabindex="-1"></a><span class="co"># plt.show(pmoths)</span></span>
<span id="cb65-2"><a href="GLMMsPython.html#cb65-2" tabindex="-1"></a><span class="co"># plt.savefig(&quot;output/moth_counts.png&quot;)</span></span></code></pre></div>
</div>
<div id="trap-locations-1" class="section level3 hasAnchor" number="4.3.3">
<h3><span class="header-section-number">4.3.3</span> Trap locations<a href="GLMMsPython.html#trap-locations-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Trial locations in relation to each other. Some trial locations are closer to each other than others.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb66-1"><a href="GLMMsPython.html#cb66-1" tabindex="-1"></a><span class="co">## average coords for each location</span></span>
<span id="cb66-2"><a href="GLMMsPython.html#cb66-2" tabindex="-1"></a>loc_coords <span class="op">=</span> datP.groupby([<span class="st">&#39;Location&#39;</span>], as_index<span class="op">=</span><span class="va">False</span>).agg({<span class="st">&#39;Latitude&#39;</span>: <span class="st">&#39;mean&#39;</span>, <span class="st">&#39;Longitude&#39;</span>: <span class="st">&#39;mean&#39;</span>})</span>
<span id="cb66-3"><a href="GLMMsPython.html#cb66-3" tabindex="-1"></a>colors <span class="op">=</span> [<span class="st">&quot;#7F3B08&quot;</span>, <span class="st">&quot;#B35806&quot;</span>, <span class="st">&quot;#E08214&quot;</span>, <span class="st">&quot;#FDB863&quot;</span>, <span class="st">&quot;#FEE0B6&quot;</span>, <span class="st">&quot;#D8DAEB&quot;</span>, <span class="st">&quot;#B2ABD2&quot;</span>, <span class="st">&quot;#8073AC&quot;</span>, <span class="st">&quot;#542788&quot;</span>, <span class="st">&quot;#2D004B&quot;</span>]</span>
<span id="cb66-4"><a href="GLMMsPython.html#cb66-4" tabindex="-1"></a></span>
<span id="cb66-5"><a href="GLMMsPython.html#cb66-5" tabindex="-1"></a>m <span class="op">=</span> StaticMap(<span class="dv">600</span>, <span class="dv">300</span>)</span>
<span id="cb66-6"><a href="GLMMsPython.html#cb66-6" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="bu">len</span>(loc_coords[<span class="st">&quot;Longitude&quot;</span>])):</span>
<span id="cb66-7"><a href="GLMMsPython.html#cb66-7" tabindex="-1"></a>  <span class="co"># add outline first to make points easier to see:</span></span>
<span id="cb66-8"><a href="GLMMsPython.html#cb66-8" tabindex="-1"></a>  m.add_marker(CircleMarker((loc_coords[<span class="st">&quot;Longitude&quot;</span>][i], loc_coords[<span class="st">&quot;Latitude&quot;</span>][i]), <span class="st">&quot;black&quot;</span>, <span class="dv">12</span>))</span>
<span id="cb66-9"><a href="GLMMsPython.html#cb66-9" tabindex="-1"></a>  m.add_marker(CircleMarker((loc_coords[<span class="st">&quot;Longitude&quot;</span>][i], loc_coords[<span class="st">&quot;Latitude&quot;</span>][i]), colors[i], <span class="dv">10</span>))</span>
<span id="cb66-10"><a href="GLMMsPython.html#cb66-10" tabindex="-1"></a></span>
<span id="cb66-11"><a href="GLMMsPython.html#cb66-11" tabindex="-1"></a>image <span class="op">=</span> m.render(zoom<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb66-12"><a href="GLMMsPython.html#cb66-12" tabindex="-1"></a>image.save(<span class="st">&#39;output/trial_locs.png&#39;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="GLMMsPython.html#cb67-1" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">&quot;output/trial_locs.png&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-2"></span>
<img src="output/trial_locs.png" alt="Example trial locations." width="100%" />
<p class="caption">
Figure 4.1: Example trial locations.
</p>
</div>
<!-- ![Trial locations](output/trial_locs.png "Trial locations.") -->
<p>Within each location, the treatment traps have a slightly different alignment:</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb68-1"><a href="GLMMsPython.html#cb68-1" tabindex="-1"></a>coords <span class="op">=</span> datP[[<span class="st">&#39;Location&#39;</span>, <span class="st">&#39;Treatment&#39;</span>, <span class="st">&#39;TrapID&#39;</span>, <span class="st">&#39;Latitude&#39;</span>, <span class="st">&#39;Longitude&#39;</span>]].drop_duplicates()</span>
<span id="cb68-2"><a href="GLMMsPython.html#cb68-2" tabindex="-1"></a><span class="co"># coords.describe(include = &#39;all&#39;)</span></span>
<span id="cb68-3"><a href="GLMMsPython.html#cb68-3" tabindex="-1"></a></span>
<span id="cb68-4"><a href="GLMMsPython.html#cb68-4" tabindex="-1"></a>pcoords <span class="op">=</span> (ggplot(datP, aes(x <span class="op">=</span> <span class="st">&#39;Longitude&#39;</span>, y<span class="op">=</span><span class="st">&#39;Latitude&#39;</span>, color <span class="op">=</span> <span class="st">&#39;Treatment&#39;</span>)) <span class="op">+</span></span>
<span id="cb68-5"><a href="GLMMsPython.html#cb68-5" tabindex="-1"></a>  geom_point() <span class="op">+</span> </span>
<span id="cb68-6"><a href="GLMMsPython.html#cb68-6" tabindex="-1"></a>  facet_wrap([<span class="st">&#39;Location&#39;</span>], scales <span class="op">=</span> <span class="st">&quot;free&quot;</span>) <span class="op">+</span></span>
<span id="cb68-7"><a href="GLMMsPython.html#cb68-7" tabindex="-1"></a>  scale_color_manual(values <span class="op">=</span> mycolors) <span class="op">+</span></span>
<span id="cb68-8"><a href="GLMMsPython.html#cb68-8" tabindex="-1"></a>  theme(aspect_ratio<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb68-9"><a href="GLMMsPython.html#cb68-9" tabindex="-1"></a>        axis_text_x<span class="op">=</span>element_blank(),</span>
<span id="cb68-10"><a href="GLMMsPython.html#cb68-10" tabindex="-1"></a>        axis_text_y<span class="op">=</span>element_blank())  <span class="op">+</span></span>
<span id="cb68-11"><a href="GLMMsPython.html#cb68-11" tabindex="-1"></a>  geom_text(aes(label <span class="op">=</span> <span class="st">&#39;TrapID&#39;</span>), nudge_x <span class="op">=</span> <span class="fl">0.0002</span>, nudge_y <span class="op">=</span> <span class="fl">0.0002</span>, color <span class="op">=</span> <span class="st">&quot;black&quot;</span>, size <span class="op">=</span> <span class="dv">8</span>) <span class="op">+</span></span>
<span id="cb68-12"><a href="GLMMsPython.html#cb68-12" tabindex="-1"></a>  scale_x_continuous(expand <span class="op">=</span> (<span class="fl">0.3</span>, <span class="dv">0</span>)) <span class="op">+</span></span>
<span id="cb68-13"><a href="GLMMsPython.html#cb68-13" tabindex="-1"></a>  scale_y_continuous(expand <span class="op">=</span> (<span class="fl">0.3</span>, <span class="dv">0</span>)) <span class="op">+</span></span>
<span id="cb68-14"><a href="GLMMsPython.html#cb68-14" tabindex="-1"></a>  labs(title <span class="op">=</span> <span class="st">&quot;Trap ID&#39;s at each location&quot;</span>))</span>
<span id="cb68-15"><a href="GLMMsPython.html#cb68-15" tabindex="-1"></a>pcoords.save(<span class="st">&quot;output/traplocs.png&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="GLMMsPython.html#cb69-1" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">&quot;output/traplocs.png&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-3"></span>
<img src="output/traplocs.png" alt="Example trial locations." width="100%" />
<p class="caption">
Figure 4.2: Example trial locations.
</p>
</div>
<!-- ![Trap coords](output/traplocs.png "Trap coordinates.") -->
</div>
</div>
<div id="fit-glmPy" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Fitted GLM models<a href="GLMMsPython.html#fit-glmPy" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To start, we ignore all the spatial and temporal relationships in the data and assume each data point is independent and identically distributed (iid). <strong>This is not a good model for the data!</strong> It is just our starting off point.</p>
<p>When building hierarchical Bayesian models, it is always a good idea to start simple, make sure everything works as expected, and then build up.</p>
<p>See Section <a href="mathematical-models.html#glm">2.1</a> for the associated mathematical models.</p>
<div id="frequentist-poisson-model-1" class="section level3 hasAnchor" number="4.4.1">
<h3><span class="header-section-number">4.4.1</span> Frequentist Poisson model<a href="GLMMsPython.html#frequentist-poisson-model-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>These models show a very tight confidence intervals for our coefficient estimates and our predictions. But also, the residual deviance is MUCH greater than the degree of freedom, indicating a lack of fit. The plot of the predictions (Figure <a href="GLMMsR.html#fig:p1p-glmFig">3.1</a>) overlaid on the data also demonstrate the lack of fit.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb70-1"><a href="GLMMsPython.html#cb70-1" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb70-2"><a href="GLMMsPython.html#cb70-2" tabindex="-1"></a><span class="im">from</span> patsy <span class="im">import</span> dmatrices <span class="co"># for dmatrices function</span></span>
<span id="cb70-3"><a href="GLMMsPython.html#cb70-3" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm <span class="co"># for regressions</span></span>
<span id="cb70-4"><a href="GLMMsPython.html#cb70-4" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb70-5"><a href="GLMMsPython.html#cb70-5" tabindex="-1"></a></span>
<span id="cb70-6"><a href="GLMMsPython.html#cb70-6" tabindex="-1"></a><span class="co"># POISSON regression</span></span>
<span id="cb70-7"><a href="GLMMsPython.html#cb70-7" tabindex="-1"></a>form <span class="op">=</span> <span class="st">&quot;&quot;&quot; nYSB ~ Treatment&quot;&quot;&quot;</span></span>
<span id="cb70-8"><a href="GLMMsPython.html#cb70-8" tabindex="-1"></a>y, X <span class="op">=</span> dmatrices(form, datP, return_type <span class="op">=</span> <span class="st">&#39;dataframe&#39;</span>)</span>
<span id="cb70-9"><a href="GLMMsPython.html#cb70-9" tabindex="-1"></a>mod1p <span class="op">=</span> sm.GLM(y, X, </span>
<span id="cb70-10"><a href="GLMMsPython.html#cb70-10" tabindex="-1"></a>              offset<span class="op">=</span>np.log(datP[<span class="st">&quot;DaysOfCatch&quot;</span>]),</span>
<span id="cb70-11"><a href="GLMMsPython.html#cb70-11" tabindex="-1"></a>              family <span class="op">=</span> sm.families.Poisson())</span>
<span id="cb70-12"><a href="GLMMsPython.html#cb70-12" tabindex="-1"></a>results1p <span class="op">=</span> mod1p.fit()</span>
<span id="cb70-13"><a href="GLMMsPython.html#cb70-13" tabindex="-1"></a><span class="bu">print</span>(results1p.summary())</span></code></pre></div>
<pre><code>##                  Generalized Linear Model Regression Results                  
## ==============================================================================
## Dep. Variable:                   nYSB   No. Observations:                  672
## Model:                            GLM   Df Residuals:                      670
## Model Family:                 Poisson   Df Model:                            1
## Link Function:                    Log   Scale:                          1.0000
## Method:                          IRLS   Log-Likelihood:                -14034.
## Date:                Thu, 03 Jul 2025   Deviance:                       25678.
## Time:                        21:35:32   Pearson chi2:                 4.24e+04
## No. Iterations:                     6   Pseudo R-squ. (CS):              1.000
## Covariance Type:            nonrobust                                         
## ====================================================================================
##                        coef    std err          z      P&gt;|z|      [0.025      0.975]
## ------------------------------------------------------------------------------------
## Intercept            1.3960      0.009    162.829      0.000       1.379       1.413
## Treatment[T.Trt]    -2.1665      0.027    -80.933      0.000      -2.219      -2.114
## ====================================================================================</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb72-1"><a href="GLMMsPython.html#cb72-1" tabindex="-1"></a><span class="co">## obtain TR estimate for comparison later (custom function in Setup code)</span></span>
<span id="cb72-2"><a href="GLMMsPython.html#cb72-2" tabindex="-1"></a>TR_1p <span class="op">=</span> getTR(results1p)</span>
<span id="cb72-3"><a href="GLMMsPython.html#cb72-3" tabindex="-1"></a><span class="bu">print</span>(TR_1p)</span></code></pre></div>
<pre><code>##     TR  lowerCI  upperCI
## 0  100      100      100</code></pre>
<p>Note: when I predict for new data, I set <span class="math inline">\(DaysOfCatch = 1\)</span>, and then I compare to the moths per day variable (<span class="math inline">\(mothsperday = nYSB / DaysOfCatch\)</span>). I want to exclude any patterns related to the varying time intervals.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb74-1"><a href="GLMMsPython.html#cb74-1" tabindex="-1"></a><span class="co"># predict from poisson regression:</span></span>
<span id="cb74-2"><a href="GLMMsPython.html#cb74-2" tabindex="-1"></a>preds1p <span class="op">=</span> results1p.get_prediction(X, which <span class="op">=</span> <span class="st">&#39;linear&#39;</span>)</span>
<span id="cb74-3"><a href="GLMMsPython.html#cb74-3" tabindex="-1"></a>preds1pDFtmp <span class="op">=</span> preds1p.summary_frame() <span class="co">#summary_frame() returns a pandas DF</span></span>
<span id="cb74-4"><a href="GLMMsPython.html#cb74-4" tabindex="-1"></a>preds1pDFtmp.describe()</span></code></pre></div>
<pre><code>##         predicted          se    ci_lower    ci_upper
## count  672.000000  672.000000  672.000000  672.000000
## mean     0.312790    0.016966    0.279536    0.346043
## std      1.084062    0.008399    1.100524    1.067600
## min     -0.770465    0.008574   -0.820168   -0.720762
## 25%     -0.770465    0.008574   -0.820168   -0.720762
## 50%      0.312790    0.016966    0.279536    0.346043
## 75%      1.396045    0.025359    1.379241    1.412849
## max      1.396045    0.025359    1.379241    1.412849</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb76-1"><a href="GLMMsPython.html#cb76-1" tabindex="-1"></a>preds1pDF <span class="op">=</span> datP</span>
<span id="cb76-2"><a href="GLMMsPython.html#cb76-2" tabindex="-1"></a>preds1pDF[<span class="st">&#39;exp_values&#39;</span>] <span class="op">=</span> preds1pDFtmp[<span class="st">&#39;predicted&#39;</span>].<span class="bu">apply</span>(math.exp)</span>
<span id="cb76-3"><a href="GLMMsPython.html#cb76-3" tabindex="-1"></a>preds1pDF[<span class="st">&#39;lowerCI&#39;</span>] <span class="op">=</span> preds1pDFtmp[<span class="st">&#39;ci_lower&#39;</span>].<span class="bu">apply</span>(math.exp)</span>
<span id="cb76-4"><a href="GLMMsPython.html#cb76-4" tabindex="-1"></a>preds1pDF[<span class="st">&#39;upperCI&#39;</span>] <span class="op">=</span> preds1pDFtmp[<span class="st">&#39;ci_upper&#39;</span>].<span class="bu">apply</span>(math.exp)</span>
<span id="cb76-5"><a href="GLMMsPython.html#cb76-5" tabindex="-1"></a></span>
<span id="cb76-6"><a href="GLMMsPython.html#cb76-6" tabindex="-1"></a><span class="co">## plot predicted and actual:</span></span>
<span id="cb76-7"><a href="GLMMsPython.html#cb76-7" tabindex="-1"></a>freqplot1p <span class="op">=</span> (ggplot(preds1pDF, </span>
<span id="cb76-8"><a href="GLMMsPython.html#cb76-8" tabindex="-1"></a>                aes(x <span class="op">=</span> <span class="st">&#39;DATI&#39;</span>, y<span class="op">=</span><span class="st">&#39;exp_values&#39;</span>, color <span class="op">=</span> <span class="st">&#39;Treatment&#39;</span>)) <span class="op">+</span></span>
<span id="cb76-9"><a href="GLMMsPython.html#cb76-9" tabindex="-1"></a>        geom_line() <span class="op">+</span></span>
<span id="cb76-10"><a href="GLMMsPython.html#cb76-10" tabindex="-1"></a>        geom_ribbon(aes(ymin <span class="op">=</span> <span class="st">&#39;lowerCI&#39;</span>, ymax <span class="op">=</span> <span class="st">&#39;upperCI&#39;</span>, fill <span class="op">=</span> <span class="st">&#39;Treatment&#39;</span>),</span>
<span id="cb76-11"><a href="GLMMsPython.html#cb76-11" tabindex="-1"></a>              alpha <span class="op">=</span> <span class="fl">0.3</span>) <span class="op">+</span></span>
<span id="cb76-12"><a href="GLMMsPython.html#cb76-12" tabindex="-1"></a>        geom_point(aes(x<span class="op">=</span><span class="st">&#39;DATI&#39;</span>, y<span class="op">=</span><span class="st">&#39;mothsperday&#39;</span>, color <span class="op">=</span> <span class="st">&#39;Treatment&#39;</span>), </span>
<span id="cb76-13"><a href="GLMMsPython.html#cb76-13" tabindex="-1"></a>            data <span class="op">=</span> mean_cts, size <span class="op">=</span> <span class="fl">1.1</span>) <span class="op">+</span></span>
<span id="cb76-14"><a href="GLMMsPython.html#cb76-14" tabindex="-1"></a>        facet_wrap([<span class="st">&#39;Location&#39;</span>], scales <span class="op">=</span> <span class="st">&quot;free_y&quot;</span>) <span class="op">+</span></span>
<span id="cb76-15"><a href="GLMMsPython.html#cb76-15" tabindex="-1"></a>        scale_color_manual(values <span class="op">=</span> mycolors) <span class="op">+</span></span>
<span id="cb76-16"><a href="GLMMsPython.html#cb76-16" tabindex="-1"></a>        scale_fill_manual(values <span class="op">=</span> mycolors) <span class="op">+</span></span>
<span id="cb76-17"><a href="GLMMsPython.html#cb76-17" tabindex="-1"></a>        labs(title <span class="op">=</span> <span class="st">&quot;Poisson GLM predictions&quot;</span>,</span>
<span id="cb76-18"><a href="GLMMsPython.html#cb76-18" tabindex="-1"></a>             subtitle <span class="op">=</span> <span class="st">&quot;Lines are predictions, points are the data&quot;</span>))</span>
<span id="cb76-19"><a href="GLMMsPython.html#cb76-19" tabindex="-1"></a>freqplot1p.draw(<span class="va">True</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:p1p-glmFigPy"></span>
<img src="03-GLMMsInPython_files/figure-html/p1p-glmFigPy-1.png" alt="Poisson GLM predictions (Python)." width="100%" />
<p class="caption">
Figure 4.3: Poisson GLM predictions (Python).
</p>
</div>
<div class="sourceCode" id="cb77"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb77-1"><a href="GLMMsPython.html#cb77-1" tabindex="-1"></a><span class="co"># freqplot1p.save(filename=&#39;freqplot1p.png&#39;, path=&#39;output/&#39;)</span></span></code></pre></div>
<p>The model is such a bad fit to the data, it is hard to even tell what is going on in the figure above.</p>
</div>
<div id="nb1Py" class="section level3 hasAnchor" number="4.4.2">
<h3><span class="header-section-number">4.4.2</span> Frequentist NB model<a href="GLMMsPython.html#nb1Py" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For the negative binomial (NB) model, our confidence intervals are a little wider, but we are still ignoring all the correlations in our data. And the plot of the predictions again indicates the lack of fit (Figure <a href="GLMMsPython.html#fig:p1nb-glmFigPy">4.4</a>).</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb78-1"><a href="GLMMsPython.html#cb78-1" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> nbinom</span>
<span id="cb78-2"><a href="GLMMsPython.html#cb78-2" tabindex="-1"></a></span>
<span id="cb78-3"><a href="GLMMsPython.html#cb78-3" tabindex="-1"></a>form <span class="op">=</span> <span class="st">&quot;&quot;&quot; nYSB ~ Treatment&quot;&quot;&quot;</span></span>
<span id="cb78-4"><a href="GLMMsPython.html#cb78-4" tabindex="-1"></a>y, X <span class="op">=</span> dmatrices(form, datP, return_type <span class="op">=</span> <span class="st">&#39;dataframe&#39;</span>)</span>
<span id="cb78-5"><a href="GLMMsPython.html#cb78-5" tabindex="-1"></a>mod1nb <span class="op">=</span> sm.NegativeBinomial(y,X, offset<span class="op">=</span>np.log(datP[<span class="st">&quot;DaysOfCatch&quot;</span>]))</span>
<span id="cb78-6"><a href="GLMMsPython.html#cb78-6" tabindex="-1"></a>results1nb <span class="op">=</span> mod1nb.fit()</span></code></pre></div>
<pre><code>## Optimization terminated successfully.
##          Current function value: 3.629123
##          Iterations: 10
##          Function evaluations: 11
##          Gradient evaluations: 11</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb80-1"><a href="GLMMsPython.html#cb80-1" tabindex="-1"></a><span class="bu">print</span>(results1nb.summary())</span></code></pre></div>
<pre><code>##                      NegativeBinomial Regression Results                      
## ==============================================================================
## Dep. Variable:                   nYSB   No. Observations:                  672
## Model:               NegativeBinomial   Df Residuals:                      670
## Method:                           MLE   Df Model:                            1
## Date:                Thu, 03 Jul 2025   Pseudo R-squ.:                 0.06445
## Time:                        21:35:34   Log-Likelihood:                -2438.8
## converged:                       True   LL-Null:                       -2606.8
## Covariance Type:            nonrobust   LLR p-value:                 4.739e-75
## ====================================================================================
##                        coef    std err          z      P&gt;|z|      [0.025      0.975]
## ------------------------------------------------------------------------------------
## Intercept            1.4023      0.068     20.651      0.000       1.269       1.535
## Treatment[T.Trt]    -2.1636      0.099    -21.863      0.000      -2.358      -1.970
## alpha                1.5244      0.082     18.628      0.000       1.364       1.685
## ====================================================================================</code></pre>
<div class="sourceCode" id="cb82"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb82-1"><a href="GLMMsPython.html#cb82-1" tabindex="-1"></a><span class="co">## obtain TR estimate for comparison later (custom function in Setup code)</span></span>
<span id="cb82-2"><a href="GLMMsPython.html#cb82-2" tabindex="-1"></a>TR_1nb <span class="op">=</span> getTR(results1nb)</span>
<span id="cb82-3"><a href="GLMMsPython.html#cb82-3" tabindex="-1"></a><span class="bu">print</span>(TR_1nb)</span></code></pre></div>
<pre><code>##     TR  lowerCI  upperCI
## 0  100      100      100</code></pre>
<div class="sourceCode" id="cb84"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb84-1"><a href="GLMMsPython.html#cb84-1" tabindex="-1"></a><span class="co">## code to predict moth counts from model:</span></span>
<span id="cb84-2"><a href="GLMMsPython.html#cb84-2" tabindex="-1"></a>preds1nb <span class="op">=</span> results1nb.get_prediction(X, which <span class="op">=</span> <span class="st">&#39;linear&#39;</span>)</span>
<span id="cb84-3"><a href="GLMMsPython.html#cb84-3" tabindex="-1"></a>preds1nbDFtmp <span class="op">=</span> preds1nb.summary_frame()</span>
<span id="cb84-4"><a href="GLMMsPython.html#cb84-4" tabindex="-1"></a>preds1nbDFtmp.describe()</span></code></pre></div>
<pre><code>##         predicted          se    ci_lower    ci_upper
## count  672.000000  672.000000  672.000000  672.000000
## mean     0.320438    0.069947    0.183344    0.457531
## std      1.082628    0.002045    1.086637    1.078620
## min     -0.761384    0.067903   -0.902484   -0.620285
## 25%     -0.761384    0.067903   -0.902484   -0.620285
## 50%      0.320438    0.069947    0.183344    0.457531
## 75%      1.402260    0.071991    1.269172    1.535348
## max      1.402260    0.071991    1.269172    1.535348</code></pre>
<div class="sourceCode" id="cb86"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb86-1"><a href="GLMMsPython.html#cb86-1" tabindex="-1"></a>preds1nbDF <span class="op">=</span> datP</span>
<span id="cb86-2"><a href="GLMMsPython.html#cb86-2" tabindex="-1"></a>preds1nbDF[<span class="st">&#39;exp_values&#39;</span>] <span class="op">=</span> preds1nbDFtmp[<span class="st">&#39;predicted&#39;</span>].<span class="bu">apply</span>(math.exp)</span>
<span id="cb86-3"><a href="GLMMsPython.html#cb86-3" tabindex="-1"></a>preds1nbDF[<span class="st">&#39;lowerCI&#39;</span>] <span class="op">=</span> preds1nbDFtmp[<span class="st">&#39;ci_lower&#39;</span>].<span class="bu">apply</span>(math.exp)</span>
<span id="cb86-4"><a href="GLMMsPython.html#cb86-4" tabindex="-1"></a>preds1nbDF[<span class="st">&#39;upperCI&#39;</span>] <span class="op">=</span> preds1nbDFtmp[<span class="st">&#39;ci_upper&#39;</span>].<span class="bu">apply</span>(math.exp)</span>
<span id="cb86-5"><a href="GLMMsPython.html#cb86-5" tabindex="-1"></a></span>
<span id="cb86-6"><a href="GLMMsPython.html#cb86-6" tabindex="-1"></a></span>
<span id="cb86-7"><a href="GLMMsPython.html#cb86-7" tabindex="-1"></a></span>
<span id="cb86-8"><a href="GLMMsPython.html#cb86-8" tabindex="-1"></a></span>
<span id="cb86-9"><a href="GLMMsPython.html#cb86-9" tabindex="-1"></a><span class="co">## plot predicted and actual:</span></span>
<span id="cb86-10"><a href="GLMMsPython.html#cb86-10" tabindex="-1"></a>freqplot1nb <span class="op">=</span> (ggplot(preds1nbDF, aes(x <span class="op">=</span> <span class="st">&#39;DATI&#39;</span>, y<span class="op">=</span><span class="st">&#39;exp_values&#39;</span>, color <span class="op">=</span> <span class="st">&#39;Treatment&#39;</span>)) <span class="op">+</span></span>
<span id="cb86-11"><a href="GLMMsPython.html#cb86-11" tabindex="-1"></a>        geom_line() <span class="op">+</span></span>
<span id="cb86-12"><a href="GLMMsPython.html#cb86-12" tabindex="-1"></a>        geom_ribbon(aes(ymin <span class="op">=</span> <span class="st">&#39;lowerCI&#39;</span>, ymax <span class="op">=</span> <span class="st">&#39;upperCI&#39;</span>, fill <span class="op">=</span> <span class="st">&#39;Treatment&#39;</span>),</span>
<span id="cb86-13"><a href="GLMMsPython.html#cb86-13" tabindex="-1"></a>              alpha <span class="op">=</span> <span class="fl">0.3</span>) <span class="op">+</span></span>
<span id="cb86-14"><a href="GLMMsPython.html#cb86-14" tabindex="-1"></a>        geom_point(aes(x<span class="op">=</span><span class="st">&#39;DATI&#39;</span>, y<span class="op">=</span><span class="st">&#39;mothsperday&#39;</span>, color <span class="op">=</span> <span class="st">&#39;Treatment&#39;</span>), </span>
<span id="cb86-15"><a href="GLMMsPython.html#cb86-15" tabindex="-1"></a>            data <span class="op">=</span> mean_cts, size <span class="op">=</span> <span class="fl">1.1</span>) <span class="op">+</span></span>
<span id="cb86-16"><a href="GLMMsPython.html#cb86-16" tabindex="-1"></a>        facet_wrap([<span class="st">&#39;Location&#39;</span>], scales <span class="op">=</span> <span class="st">&quot;free_y&quot;</span>) <span class="op">+</span></span>
<span id="cb86-17"><a href="GLMMsPython.html#cb86-17" tabindex="-1"></a>        scale_color_manual(values <span class="op">=</span> mycolors) <span class="op">+</span></span>
<span id="cb86-18"><a href="GLMMsPython.html#cb86-18" tabindex="-1"></a>        scale_fill_manual(values <span class="op">=</span> mycolors) <span class="op">+</span></span>
<span id="cb86-19"><a href="GLMMsPython.html#cb86-19" tabindex="-1"></a>        labs(title <span class="op">=</span> <span class="st">&quot;Negative binomial GLM predictions&quot;</span>,</span>
<span id="cb86-20"><a href="GLMMsPython.html#cb86-20" tabindex="-1"></a>             subtitle <span class="op">=</span> <span class="st">&quot;Lines are predictions, points are the data&quot;</span>))</span>
<span id="cb86-21"><a href="GLMMsPython.html#cb86-21" tabindex="-1"></a></span>
<span id="cb86-22"><a href="GLMMsPython.html#cb86-22" tabindex="-1"></a>freqplot1nb.draw(<span class="va">True</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:p1nb-glmFigPy"></span>
<img src="03-GLMMsInPython_files/figure-html/p1nb-glmFigPy-3.png" alt="Negative binomial GLM predictions (Python)." width="100%" />
<p class="caption">
Figure 4.4: Negative binomial GLM predictions (Python).
</p>
</div>
<div class="sourceCode" id="cb87"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb87-1"><a href="GLMMsPython.html#cb87-1" tabindex="-1"></a>freqplot1nb.save(filename<span class="op">=</span><span class="st">&quot;freqplot1nb.png&quot;</span>, path <span class="op">=</span> <span class="st">&quot;./output/&quot;</span>)</span></code></pre></div>
</div>
<div id="bayesian-bambi-model" class="section level3 hasAnchor" number="4.4.3">
<h3><span class="header-section-number">4.4.3</span> Bayesian (bambi) model<a href="GLMMsPython.html#bayesian-bambi-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><code>Bambi</code> is the Python module that is <em>very</em> similar to <code>brms</code> package in R. I am pretty sure the defaults use different algorithms though (which may affect your results), so be sure to read up on the details of both! However, both run <code>stan</code> on the back-end for the MCMC algorithms.</p>
<p>Because the models take a few minutes to fit, I usually fit them when I am initially running through my code, save them, and then only load the model fit when rendering the Rmarkdown file and creating the resulting figures.</p>
<p><code>Bambi</code> creates InferenceData objects. Read the <a href="https://python.arviz.org/en/latest/getting_started/WorkingWithInferenceData.html#">reference guide</a>– it is very helpful!</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb88-1"><a href="GLMMsPython.html#cb88-1" tabindex="-1"></a><span class="co"># https://bambinos.github.io/bambi/notebooks/negative_binomial.html</span></span>
<span id="cb88-2"><a href="GLMMsPython.html#cb88-2" tabindex="-1"></a><span class="im">import</span> bambi <span class="im">as</span> bmb</span>
<span id="cb88-3"><a href="GLMMsPython.html#cb88-3" tabindex="-1"></a><span class="co">## build the model:</span></span>
<span id="cb88-4"><a href="GLMMsPython.html#cb88-4" tabindex="-1"></a>model_bmb1nb <span class="op">=</span> bmb.Model(<span class="st">&quot;nYSB ~ Treatment + offset(log(DaysOfCatch))&quot;</span>, </span>
<span id="cb88-5"><a href="GLMMsPython.html#cb88-5" tabindex="-1"></a>                    datP, family<span class="op">=</span><span class="st">&quot;negativebinomial&quot;</span>,</span>
<span id="cb88-6"><a href="GLMMsPython.html#cb88-6" tabindex="-1"></a>                    priors <span class="op">=</span> {</span>
<span id="cb88-7"><a href="GLMMsPython.html#cb88-7" tabindex="-1"></a>                        <span class="st">&quot;Intercept&quot;</span>: bmb.Prior(<span class="st">&quot;Normal&quot;</span>, mu <span class="op">=</span> <span class="dv">0</span>, sigma <span class="op">=</span> <span class="dv">2</span>),</span>
<span id="cb88-8"><a href="GLMMsPython.html#cb88-8" tabindex="-1"></a>                        <span class="st">&quot;Treatment&quot;</span>: bmb.Prior(<span class="st">&quot;Normal&quot;</span>, mu <span class="op">=</span> <span class="dv">0</span>, sigma <span class="op">=</span> <span class="dv">2</span>),</span>
<span id="cb88-9"><a href="GLMMsPython.html#cb88-9" tabindex="-1"></a>                        <span class="st">&quot;alpha&quot;</span>: bmb.Prior(<span class="st">&quot;HalfCauchy&quot;</span>, beta <span class="op">=</span> <span class="dv">1</span>)</span>
<span id="cb88-10"><a href="GLMMsPython.html#cb88-10" tabindex="-1"></a>                    })</span>
<span id="cb88-11"><a href="GLMMsPython.html#cb88-11" tabindex="-1"></a>filename <span class="op">=</span> <span class="st">&#39;output/idata_bmb1nb.pkl&#39;</span></span></code></pre></div>
<div class="sourceCode" id="cb89"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb89-1"><a href="GLMMsPython.html#cb89-1" tabindex="-1"></a><span class="co">## not run</span></span>
<span id="cb89-2"><a href="GLMMsPython.html#cb89-2" tabindex="-1"></a><span class="im">import</span> bambi <span class="im">as</span> bmb</span>
<span id="cb89-3"><a href="GLMMsPython.html#cb89-3" tabindex="-1"></a><span class="co">## fit the model:</span></span>
<span id="cb89-4"><a href="GLMMsPython.html#cb89-4" tabindex="-1"></a>idata_bmb1nb <span class="op">=</span> model_bmb1nb.fit(tune <span class="op">=</span> <span class="dv">500</span>, draws<span class="op">=</span><span class="dv">2000</span>, chains<span class="op">=</span><span class="dv">6</span>, random_seed <span class="op">=</span> <span class="dv">5000</span>)</span>
<span id="cb89-5"><a href="GLMMsPython.html#cb89-5" tabindex="-1"></a><span class="co"># tune = warmup; draws = iter</span></span>
<span id="cb89-6"><a href="GLMMsPython.html#cb89-6" tabindex="-1"></a><span class="bu">print</span>(az.summary(idata_bmb1nb))</span>
<span id="cb89-7"><a href="GLMMsPython.html#cb89-7" tabindex="-1"></a></span>
<span id="cb89-8"><a href="GLMMsPython.html#cb89-8" tabindex="-1"></a><span class="co"># save bambi object to file.</span></span>
<span id="cb89-9"><a href="GLMMsPython.html#cb89-9" tabindex="-1"></a><span class="im">import</span> pickle </span>
<span id="cb89-10"><a href="GLMMsPython.html#cb89-10" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(filename, <span class="st">&#39;wb&#39;</span>) <span class="im">as</span> <span class="bu">file</span>:</span>
<span id="cb89-11"><a href="GLMMsPython.html#cb89-11" tabindex="-1"></a>    pickle.dump(idata_bmb1nb, <span class="bu">file</span>)</span></code></pre></div>
<div class="sourceCode" id="cb90"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb90-1"><a href="GLMMsPython.html#cb90-1" tabindex="-1"></a><span class="im">import</span> arviz <span class="im">as</span> az</span>
<span id="cb90-2"><a href="GLMMsPython.html#cb90-2" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt </span>
<span id="cb90-3"><a href="GLMMsPython.html#cb90-3" tabindex="-1"></a><span class="im">import</span> pickle</span>
<span id="cb90-4"><a href="GLMMsPython.html#cb90-4" tabindex="-1"></a></span>
<span id="cb90-5"><a href="GLMMsPython.html#cb90-5" tabindex="-1"></a><span class="co"># Load the object from the file</span></span>
<span id="cb90-6"><a href="GLMMsPython.html#cb90-6" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(filename, <span class="st">&#39;rb&#39;</span>) <span class="im">as</span> <span class="bu">file</span>:</span>
<span id="cb90-7"><a href="GLMMsPython.html#cb90-7" tabindex="-1"></a>    idata_bmb1nb <span class="op">=</span> pickle.load(<span class="bu">file</span>)</span>
<span id="cb90-8"><a href="GLMMsPython.html#cb90-8" tabindex="-1"></a></span>
<span id="cb90-9"><a href="GLMMsPython.html#cb90-9" tabindex="-1"></a><span class="co"># to see the priors:</span></span>
<span id="cb90-10"><a href="GLMMsPython.html#cb90-10" tabindex="-1"></a><span class="co"># model_bmb1nb</span></span>
<span id="cb90-11"><a href="GLMMsPython.html#cb90-11" tabindex="-1"></a></span>
<span id="cb90-12"><a href="GLMMsPython.html#cb90-12" tabindex="-1"></a><span class="co"># summary stats</span></span>
<span id="cb90-13"><a href="GLMMsPython.html#cb90-13" tabindex="-1"></a><span class="bu">print</span>(az.summary(idata_bmb1nb))</span></code></pre></div>
<pre><code>##                  mean     sd  hdi_3%  hdi_97%  mcse_mean  mcse_sd  ess_bulk  \
## alpha           0.656  0.035   0.588    0.721      0.000    0.000   17917.0   
## Intercept       1.402  0.067   1.276    1.530      0.000    0.001   18638.0   
## Treatment[Trt] -2.159  0.099  -2.343   -1.974      0.001    0.001   17245.0   
## 
##                 ess_tail  r_hat  
## alpha             8766.0    1.0  
## Intercept         9286.0    1.0  
## Treatment[Trt]   10039.0    1.0</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb92-1"><a href="GLMMsPython.html#cb92-1" tabindex="-1"></a><span class="co"># CALC TR:</span></span>
<span id="cb92-2"><a href="GLMMsPython.html#cb92-2" tabindex="-1"></a>b1 <span class="op">=</span> idata_bmb1nb.posterior[<span class="st">&quot;Treatment&quot;</span>].stack(sample<span class="op">=</span>(<span class="st">&quot;chain&quot;</span>, <span class="st">&quot;draw&quot;</span>)).to_dataframe(name <span class="op">=</span> <span class="st">&quot;Trt&quot;</span>)</span>
<span id="cb92-3"><a href="GLMMsPython.html#cb92-3" tabindex="-1"></a></span>
<span id="cb92-4"><a href="GLMMsPython.html#cb92-4" tabindex="-1"></a>TR1nb <span class="op">=</span> <span class="dv">100</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> np.exp(b1[<span class="st">&#39;Trt&#39;</span>]))</span>
<span id="cb92-5"><a href="GLMMsPython.html#cb92-5" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">round</span>(TR1nb.quantile(q<span class="op">=</span>[<span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span>])))</span></code></pre></div>
<pre><code>## 0.025    86.0
## 0.500    88.0
## 0.975    90.0
## Name: Trt, dtype: float64</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb94-1"><a href="GLMMsPython.html#cb94-1" tabindex="-1"></a><span class="co"># Plot the predictions</span></span>
<span id="cb94-2"><a href="GLMMsPython.html#cb94-2" tabindex="-1"></a><span class="co"># Make predictions of the mean without offset effect:</span></span>
<span id="cb94-3"><a href="GLMMsPython.html#cb94-3" tabindex="-1"></a>bmbPreds1nb <span class="op">=</span> datP.copy() <span class="co">## IMPORTANT DIFF FROM R!!!</span></span>
<span id="cb94-4"><a href="GLMMsPython.html#cb94-4" tabindex="-1"></a><span class="co">## if newdf = olddf, changes to newdf affect olddf!!!</span></span>
<span id="cb94-5"><a href="GLMMsPython.html#cb94-5" tabindex="-1"></a>bmbPreds1nb[<span class="st">&quot;DaysOfCatch&quot;</span>] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb94-6"><a href="GLMMsPython.html#cb94-6" tabindex="-1"></a>predictions1nb <span class="op">=</span> model_bmb1nb.predict(idata_bmb1nb, data<span class="op">=</span>bmbPreds1nb, kind <span class="op">=</span> <span class="st">&quot;response_params&quot;</span>, inplace <span class="op">=</span> <span class="va">False</span>)</span>
<span id="cb94-7"><a href="GLMMsPython.html#cb94-7" tabindex="-1"></a>post1nb <span class="op">=</span> predictions1nb.posterior</span>
<span id="cb94-8"><a href="GLMMsPython.html#cb94-8" tabindex="-1"></a>post1nb</span></code></pre></div>
<div><svg style="position: absolute; width: 0; height: 0; overflow: hidden">
<defs>
<symbol id="icon-database" viewBox="0 0 32 32">
<path d="M16 0c-8.837 0-16 2.239-16 5v4c0 2.761 7.163 5 16 5s16-2.239 16-5v-4c0-2.761-7.163-5-16-5z"></path>
<path d="M16 17c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
<path d="M16 26c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
</symbol>
<symbol id="icon-file-text2" viewBox="0 0 32 32">
<path d="M28.681 7.159c-0.694-0.947-1.662-2.053-2.724-3.116s-2.169-2.030-3.116-2.724c-1.612-1.182-2.393-1.319-2.841-1.319h-15.5c-1.378 0-2.5 1.121-2.5 2.5v27c0 1.378 1.122 2.5 2.5 2.5h23c1.378 0 2.5-1.122 2.5-2.5v-19.5c0-0.448-0.137-1.23-1.319-2.841zM24.543 5.457c0.959 0.959 1.712 1.825 2.268 2.543h-4.811v-4.811c0.718 0.556 1.584 1.309 2.543 2.268zM28 29.5c0 0.271-0.229 0.5-0.5 0.5h-23c-0.271 0-0.5-0.229-0.5-0.5v-27c0-0.271 0.229-0.5 0.5-0.5 0 0 15.499-0 15.5 0v7c0 0.552 0.448 1 1 1h7v19.5z"></path>
<path d="M23 26h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 22h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 18h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
</symbol>
</defs>
</svg>
<style>/* CSS stylesheet for displaying xarray objects in jupyterlab.
 *
 */

:root {
  --xr-font-color0: var(--jp-content-font-color0, rgba(0, 0, 0, 1));
  --xr-font-color2: var(--jp-content-font-color2, rgba(0, 0, 0, 0.54));
  --xr-font-color3: var(--jp-content-font-color3, rgba(0, 0, 0, 0.38));
  --xr-border-color: var(--jp-border-color2, #e0e0e0);
  --xr-disabled-color: var(--jp-layout-color3, #bdbdbd);
  --xr-background-color: var(--jp-layout-color0, white);
  --xr-background-color-row-even: var(--jp-layout-color1, white);
  --xr-background-color-row-odd: var(--jp-layout-color2, #eeeeee);
}

html[theme="dark"],
html[data-theme="dark"],
body[data-theme="dark"],
body.vscode-dark {
  --xr-font-color0: rgba(255, 255, 255, 1);
  --xr-font-color2: rgba(255, 255, 255, 0.54);
  --xr-font-color3: rgba(255, 255, 255, 0.38);
  --xr-border-color: #1f1f1f;
  --xr-disabled-color: #515151;
  --xr-background-color: #111111;
  --xr-background-color-row-even: #111111;
  --xr-background-color-row-odd: #313131;
}

.xr-wrap {
  display: block !important;
  min-width: 300px;
  max-width: 700px;
}

.xr-text-repr-fallback {
  /* fallback to plain text repr when CSS is not injected (untrusted notebook) */
  display: none;
}

.xr-header {
  padding-top: 6px;
  padding-bottom: 6px;
  margin-bottom: 4px;
  border-bottom: solid 1px var(--xr-border-color);
}

.xr-header > div,
.xr-header > ul {
  display: inline;
  margin-top: 0;
  margin-bottom: 0;
}

.xr-obj-type,
.xr-array-name {
  margin-left: 2px;
  margin-right: 10px;
}

.xr-obj-type {
  color: var(--xr-font-color2);
}

.xr-sections {
  padding-left: 0 !important;
  display: grid;
  grid-template-columns: 150px auto auto 1fr 0 20px 0 20px;
}

.xr-section-item {
  display: contents;
}

.xr-section-item input {
  display: inline-block;
  opacity: 0;
  height: 0;
}

.xr-section-item input + label {
  color: var(--xr-disabled-color);
}

.xr-section-item input:enabled + label {
  cursor: pointer;
  color: var(--xr-font-color2);
}

.xr-section-item input:focus + label {
  border: 2px solid var(--xr-font-color0);
}

.xr-section-item input:enabled + label:hover {
  color: var(--xr-font-color0);
}

.xr-section-summary {
  grid-column: 1;
  color: var(--xr-font-color2);
  font-weight: 500;
}

.xr-section-summary > span {
  display: inline-block;
  padding-left: 0.5em;
}

.xr-section-summary-in:disabled + label {
  color: var(--xr-font-color2);
}

.xr-section-summary-in + label:before {
  display: inline-block;
  content: "►";
  font-size: 11px;
  width: 15px;
  text-align: center;
}

.xr-section-summary-in:disabled + label:before {
  color: var(--xr-disabled-color);
}

.xr-section-summary-in:checked + label:before {
  content: "▼";
}

.xr-section-summary-in:checked + label > span {
  display: none;
}

.xr-section-summary,
.xr-section-inline-details {
  padding-top: 4px;
  padding-bottom: 4px;
}

.xr-section-inline-details {
  grid-column: 2 / -1;
}

.xr-section-details {
  display: none;
  grid-column: 1 / -1;
  margin-bottom: 5px;
}

.xr-section-summary-in:checked ~ .xr-section-details {
  display: contents;
}

.xr-array-wrap {
  grid-column: 1 / -1;
  display: grid;
  grid-template-columns: 20px auto;
}

.xr-array-wrap > label {
  grid-column: 1;
  vertical-align: top;
}

.xr-preview {
  color: var(--xr-font-color3);
}

.xr-array-preview,
.xr-array-data {
  padding: 0 5px !important;
  grid-column: 2;
}

.xr-array-data,
.xr-array-in:checked ~ .xr-array-preview {
  display: none;
}

.xr-array-in:checked ~ .xr-array-data,
.xr-array-preview {
  display: inline-block;
}

.xr-dim-list {
  display: inline-block !important;
  list-style: none;
  padding: 0 !important;
  margin: 0;
}

.xr-dim-list li {
  display: inline-block;
  padding: 0;
  margin: 0;
}

.xr-dim-list:before {
  content: "(";
}

.xr-dim-list:after {
  content: ")";
}

.xr-dim-list li:not(:last-child):after {
  content: ",";
  padding-right: 5px;
}

.xr-has-index {
  font-weight: bold;
}

.xr-var-list,
.xr-var-item {
  display: contents;
}

.xr-var-item > div,
.xr-var-item label,
.xr-var-item > .xr-var-name span {
  background-color: var(--xr-background-color-row-even);
  margin-bottom: 0;
}

.xr-var-item > .xr-var-name:hover span {
  padding-right: 5px;
}

.xr-var-list > li:nth-child(odd) > div,
.xr-var-list > li:nth-child(odd) > label,
.xr-var-list > li:nth-child(odd) > .xr-var-name span {
  background-color: var(--xr-background-color-row-odd);
}

.xr-var-name {
  grid-column: 1;
}

.xr-var-dims {
  grid-column: 2;
}

.xr-var-dtype {
  grid-column: 3;
  text-align: right;
  color: var(--xr-font-color2);
}

.xr-var-preview {
  grid-column: 4;
}

.xr-index-preview {
  grid-column: 2 / 5;
  color: var(--xr-font-color2);
}

.xr-var-name,
.xr-var-dims,
.xr-var-dtype,
.xr-preview,
.xr-attrs dt {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  padding-right: 10px;
}

.xr-var-name:hover,
.xr-var-dims:hover,
.xr-var-dtype:hover,
.xr-attrs dt:hover {
  overflow: visible;
  width: auto;
  z-index: 1;
}

.xr-var-attrs,
.xr-var-data,
.xr-index-data {
  display: none;
  background-color: var(--xr-background-color) !important;
  padding-bottom: 5px !important;
}

.xr-var-attrs-in:checked ~ .xr-var-attrs,
.xr-var-data-in:checked ~ .xr-var-data,
.xr-index-data-in:checked ~ .xr-index-data {
  display: block;
}

.xr-var-data > table {
  float: right;
}

.xr-var-name span,
.xr-var-data,
.xr-index-name div,
.xr-index-data,
.xr-attrs {
  padding-left: 25px !important;
}

.xr-attrs,
.xr-var-attrs,
.xr-var-data,
.xr-index-data {
  grid-column: 1 / -1;
}

dl.xr-attrs {
  padding: 0;
  margin: 0;
  display: grid;
  grid-template-columns: 125px auto;
}

.xr-attrs dt,
.xr-attrs dd {
  padding: 0;
  margin: 0;
  float: left;
  padding-right: 10px;
  width: auto;
}

.xr-attrs dt {
  font-weight: normal;
  grid-column: 1;
}

.xr-attrs dt:hover span {
  display: inline-block;
  background: var(--xr-background-color);
  padding-right: 10px;
}

.xr-attrs dd {
  grid-column: 2;
  white-space: pre-wrap;
  word-break: break-all;
}

.xr-icon-database,
.xr-icon-file-text2,
.xr-no-icon {
  display: inline-block;
  vertical-align: middle;
  width: 1em;
  height: 1.5em !important;
  stroke-width: 0;
  stroke: currentColor;
  fill: currentColor;
}
</style><pre class='xr-text-repr-fallback'>&lt;xarray.Dataset&gt; Size: 65MB
Dimensions:        (chain: 6, draw: 2000, Treatment_dim: 1, __obs__: 672)
Coordinates:
  * chain          (chain) int64 48B 0 1 2 3 4 5
  * draw           (draw) int64 16kB 0 1 2 3 4 5 ... 1995 1996 1997 1998 1999
  * Treatment_dim  (Treatment_dim) &lt;U3 12B &#x27;Trt&#x27;
  * __obs__        (__obs__) int64 5kB 0 1 2 3 4 5 6 ... 666 667 668 669 670 671
Data variables:
    alpha          (chain, draw) float64 96kB 0.6959 0.6361 ... 0.6491 0.691
    Intercept      (chain, draw) float64 96kB 1.245 1.477 1.368 ... 1.411 1.401
    Treatment      (chain, draw, Treatment_dim) float64 96kB -2.08 ... -2.131
    mu             (chain, draw, __obs__) float64 65MB 0.4342 0.4342 ... 4.058
Attributes:
    created_at:                  2025-07-01T16:14:29.892205+00:00
    arviz_version:               0.21.0
    inference_library:           pymc
    inference_library_version:   5.22.0
    sampling_time:               18.31052279472351
    tuning_steps:                500
    modeling_interface:          bambi
    modeling_interface_version:  0.15.0</pre><div class='xr-wrap' style='display:none'><div class='xr-header'><div class='xr-obj-type'>xarray.Dataset</div></div><ul class='xr-sections'><li class='xr-section-item'><input id='section-74dccb94-9e8d-44f9-be82-2b7718751ae8' class='xr-section-summary-in' type='checkbox' disabled ><label for='section-74dccb94-9e8d-44f9-be82-2b7718751ae8' class='xr-section-summary'  title='Expand/collapse section'>Dimensions:</label><div class='xr-section-inline-details'><ul class='xr-dim-list'><li><span class='xr-has-index'>chain</span>: 6</li><li><span class='xr-has-index'>draw</span>: 2000</li><li><span class='xr-has-index'>Treatment_dim</span>: 1</li><li><span class='xr-has-index'>__obs__</span>: 672</li></ul></div><div class='xr-section-details'></div></li><li class='xr-section-item'><input id='section-99756cb3-5828-4240-8a84-e2ba3dc37ca4' class='xr-section-summary-in' type='checkbox'  checked><label for='section-99756cb3-5828-4240-8a84-e2ba3dc37ca4' class='xr-section-summary' >Coordinates: <span>(4)</span></label><div class='xr-section-inline-details'></div><div class='xr-section-details'><ul class='xr-var-list'><li class='xr-var-item'><div class='xr-var-name'><span class='xr-has-index'>chain</span></div><div class='xr-var-dims'>(chain)</div><div class='xr-var-dtype'>int64</div><div class='xr-var-preview xr-preview'>0 1 2 3 4 5</div><input id='attrs-040cd9b7-4193-484c-baca-6bca570665b9' class='xr-var-attrs-in' type='checkbox' disabled><label for='attrs-040cd9b7-4193-484c-baca-6bca570665b9' title='Show/Hide attributes'><svg class='icon xr-icon-file-text2'><use xlink:href='#icon-file-text2'></use></svg></label><input id='data-8e5600bb-eb2b-472f-864f-e5ca18ac854d' class='xr-var-data-in' type='checkbox'><label for='data-8e5600bb-eb2b-472f-864f-e5ca18ac854d' title='Show/Hide data repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-var-attrs'><dl class='xr-attrs'></dl></div><div class='xr-var-data'><pre>array([0, 1, 2, 3, 4, 5])</pre></div></li><li class='xr-var-item'><div class='xr-var-name'><span class='xr-has-index'>draw</span></div><div class='xr-var-dims'>(draw)</div><div class='xr-var-dtype'>int64</div><div class='xr-var-preview xr-preview'>0 1 2 3 4 ... 1996 1997 1998 1999</div><input id='attrs-cf41b7f1-74ba-466a-bb14-6452645af1bc' class='xr-var-attrs-in' type='checkbox' disabled><label for='attrs-cf41b7f1-74ba-466a-bb14-6452645af1bc' title='Show/Hide attributes'><svg class='icon xr-icon-file-text2'><use xlink:href='#icon-file-text2'></use></svg></label><input id='data-d77f2f0b-1cdf-43b1-8bb9-d03a21ccb003' class='xr-var-data-in' type='checkbox'><label for='data-d77f2f0b-1cdf-43b1-8bb9-d03a21ccb003' title='Show/Hide data repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-var-attrs'><dl class='xr-attrs'></dl></div><div class='xr-var-data'><pre>array([   0,    1,    2, ..., 1997, 1998, 1999])</pre></div></li><li class='xr-var-item'><div class='xr-var-name'><span class='xr-has-index'>Treatment_dim</span></div><div class='xr-var-dims'>(Treatment_dim)</div><div class='xr-var-dtype'>&lt;U3</div><div class='xr-var-preview xr-preview'>&#x27;Trt&#x27;</div><input id='attrs-7e445e33-6397-45f0-818c-4aa5bccfbdfe' class='xr-var-attrs-in' type='checkbox' disabled><label for='attrs-7e445e33-6397-45f0-818c-4aa5bccfbdfe' title='Show/Hide attributes'><svg class='icon xr-icon-file-text2'><use xlink:href='#icon-file-text2'></use></svg></label><input id='data-a4d8565d-07b3-4f19-bdb6-9c5cc8ed7860' class='xr-var-data-in' type='checkbox'><label for='data-a4d8565d-07b3-4f19-bdb6-9c5cc8ed7860' title='Show/Hide data repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-var-attrs'><dl class='xr-attrs'></dl></div><div class='xr-var-data'><pre>array([&#x27;Trt&#x27;], dtype=&#x27;&lt;U3&#x27;)</pre></div></li><li class='xr-var-item'><div class='xr-var-name'><span class='xr-has-index'>__obs__</span></div><div class='xr-var-dims'>(__obs__)</div><div class='xr-var-dtype'>int64</div><div class='xr-var-preview xr-preview'>0 1 2 3 4 5 ... 667 668 669 670 671</div><input id='attrs-eff7db62-9fae-4063-b675-b72a37c77b52' class='xr-var-attrs-in' type='checkbox' disabled><label for='attrs-eff7db62-9fae-4063-b675-b72a37c77b52' title='Show/Hide attributes'><svg class='icon xr-icon-file-text2'><use xlink:href='#icon-file-text2'></use></svg></label><input id='data-00274e71-6e0b-4954-aa19-bdaf1c9dad26' class='xr-var-data-in' type='checkbox'><label for='data-00274e71-6e0b-4954-aa19-bdaf1c9dad26' title='Show/Hide data repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-var-attrs'><dl class='xr-attrs'></dl></div><div class='xr-var-data'><pre>array([  0,   1,   2, ..., 669, 670, 671])</pre></div></li></ul></div></li><li class='xr-section-item'><input id='section-c0ec1f7e-25b2-4cfc-b7ac-5b1521153345' class='xr-section-summary-in' type='checkbox'  checked><label for='section-c0ec1f7e-25b2-4cfc-b7ac-5b1521153345' class='xr-section-summary' >Data variables: <span>(4)</span></label><div class='xr-section-inline-details'></div><div class='xr-section-details'><ul class='xr-var-list'><li class='xr-var-item'><div class='xr-var-name'><span>alpha</span></div><div class='xr-var-dims'>(chain, draw)</div><div class='xr-var-dtype'>float64</div><div class='xr-var-preview xr-preview'>0.6959 0.6361 ... 0.6491 0.691</div><input id='attrs-fe7d0d29-17ee-48fe-b1ac-fbe088b5676c' class='xr-var-attrs-in' type='checkbox' disabled><label for='attrs-fe7d0d29-17ee-48fe-b1ac-fbe088b5676c' title='Show/Hide attributes'><svg class='icon xr-icon-file-text2'><use xlink:href='#icon-file-text2'></use></svg></label><input id='data-7847deb4-80a4-48db-bea1-39601710a8ff' class='xr-var-data-in' type='checkbox'><label for='data-7847deb4-80a4-48db-bea1-39601710a8ff' title='Show/Hide data repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-var-attrs'><dl class='xr-attrs'></dl></div><div class='xr-var-data'><pre>array([[0.69592703, 0.63605533, 0.68620635, ..., 0.67095042, 0.62715063,
        0.63786114],
       [0.65986889, 0.61794149, 0.65993102, ..., 0.62901943, 0.62618106,
        0.65830356],
       [0.62161161, 0.70600395, 0.63201368, ..., 0.6519154 , 0.66680872,
        0.66680872],
       [0.62065139, 0.71446181, 0.65351111, ..., 0.62456883, 0.61325715,
        0.67524612],
       [0.607845  , 0.60197837, 0.62735625, ..., 0.62053682, 0.69257234,
        0.70191768],
       [0.56194368, 0.73219812, 0.63673422, ..., 0.64910599, 0.64910599,
        0.69098746]])</pre></div></li><li class='xr-var-item'><div class='xr-var-name'><span>Intercept</span></div><div class='xr-var-dims'>(chain, draw)</div><div class='xr-var-dtype'>float64</div><div class='xr-var-preview xr-preview'>1.245 1.477 1.368 ... 1.411 1.401</div><input id='attrs-27c30e34-653f-49b0-8e3d-4b5d477c33c7' class='xr-var-attrs-in' type='checkbox' disabled><label for='attrs-27c30e34-653f-49b0-8e3d-4b5d477c33c7' title='Show/Hide attributes'><svg class='icon xr-icon-file-text2'><use xlink:href='#icon-file-text2'></use></svg></label><input id='data-82a4e2d3-77d3-43aa-af71-bd8287fe1ae6' class='xr-var-data-in' type='checkbox'><label for='data-82a4e2d3-77d3-43aa-af71-bd8287fe1ae6' title='Show/Hide data repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-var-attrs'><dl class='xr-attrs'></dl></div><div class='xr-var-data'><pre>array([[1.24536263, 1.47708429, 1.36814688, ..., 1.50729605, 1.29322517,
        1.47270335],
       [1.39617005, 1.37951911, 1.38522232, ..., 1.32313883, 1.41031622,
        1.37780825],
       [1.40453443, 1.37190486, 1.29319003, ..., 1.49329711, 1.39906769,
        1.39906769],
       [1.38311203, 1.35626315, 1.50519536, ..., 1.45597232, 1.47502733,
        1.34754421],
       [1.36842139, 1.3211883 , 1.53664426, ..., 1.43642213, 1.3891655 ,
        1.34097588],
       [1.41683807, 1.46274752, 1.34210863, ..., 1.41098516, 1.41098516,
        1.40057405]])</pre></div></li><li class='xr-var-item'><div class='xr-var-name'><span>Treatment</span></div><div class='xr-var-dims'>(chain, draw, Treatment_dim)</div><div class='xr-var-dtype'>float64</div><div class='xr-var-preview xr-preview'>-2.08 -2.272 ... -2.194 -2.131</div><input id='attrs-13035d67-b3dd-4b43-8614-335194057b68' class='xr-var-attrs-in' type='checkbox' disabled><label for='attrs-13035d67-b3dd-4b43-8614-335194057b68' title='Show/Hide attributes'><svg class='icon xr-icon-file-text2'><use xlink:href='#icon-file-text2'></use></svg></label><input id='data-baa4a12c-1645-48fd-9805-bc5cdaddd7e5' class='xr-var-data-in' type='checkbox'><label for='data-baa4a12c-1645-48fd-9805-bc5cdaddd7e5' title='Show/Hide data repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-var-attrs'><dl class='xr-attrs'></dl></div><div class='xr-var-data'><pre>array([[[-2.07969894],
        [-2.27219906],
        [-2.1526889 ],
        ...,
        [-2.32295151],
        [-1.99334357],
        [-2.16817928]],

       [[-2.1346668 ],
        [-2.18258336],
        [-2.13445219],
        ...,
        [-2.12441016],
        [-2.14952773],
        [-2.18457415]],

       [[-2.17202482],
        [-2.15490867],
        [-2.02312125],
        ...,
...
        ...,
        [-2.14453903],
        [-2.17399693],
        [-2.0719257 ]],

       [[-2.00791929],
        [-2.16919599],
        [-2.36357041],
        ...,
        [-2.16563422],
        [-2.14923385],
        [-2.13845282]],

       [[-2.0974468 ],
        [-2.19203851],
        [-2.25314854],
        ...,
        [-2.1944862 ],
        [-2.1944862 ],
        [-2.13071552]]])</pre></div></li><li class='xr-var-item'><div class='xr-var-name'><span>mu</span></div><div class='xr-var-dims'>(chain, draw, __obs__)</div><div class='xr-var-dtype'>float64</div><div class='xr-var-preview xr-preview'>0.4342 0.4342 ... 4.058 4.058</div><input id='attrs-2cba05a7-fe6f-4440-935f-abcb4170bd50' class='xr-var-attrs-in' type='checkbox' disabled><label for='attrs-2cba05a7-fe6f-4440-935f-abcb4170bd50' title='Show/Hide attributes'><svg class='icon xr-icon-file-text2'><use xlink:href='#icon-file-text2'></use></svg></label><input id='data-6184f456-7431-4e6e-896b-b70e04c4deb4' class='xr-var-data-in' type='checkbox'><label for='data-6184f456-7431-4e6e-896b-b70e04c4deb4' title='Show/Hide data repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-var-attrs'><dl class='xr-attrs'></dl></div><div class='xr-var-data'><pre>array([[[0.43416253, 0.43416253, 0.43416253, ..., 3.47419441,
         3.47419441, 3.47419441],
        [0.45152941, 0.45152941, 0.45152941, ..., 4.38015576,
         4.38015576, 4.38015576],
        [0.45632865, 0.45632865, 0.45632865, ..., 3.92806479,
         3.92806479, 3.92806479],
        ...,
        [0.44234929, 0.44234929, 0.44234929, ..., 4.51450727,
         4.51450727, 4.51450727],
        [0.49652651, 0.49652651, 0.49652651, ..., 3.64452181,
         3.64452181, 3.64452181],
        [0.49883698, 0.49883698, 0.49883698, ..., 4.36100857,
         4.36100857, 4.36100857]],

       [[0.47783168, 0.47783168, 0.47783168, ..., 4.03969846,
         4.03969846, 4.03969846],
        [0.44795421, 0.44795421, 0.44795421, ..., 3.97299058,
         3.97299058, 3.97299058],
        [0.47273048, 0.47273048, 0.47273048, ..., 3.99571412,
         3.99571412, 3.99571412],
...
        [0.48228885, 0.48228885, 0.48228885, ..., 4.20562172,
         4.20562172, 4.20562172],
        [0.46763447, 0.46763447, 0.46763447, ..., 4.01150106,
         4.01150106, 4.01150106],
        [0.45046408, 0.45046408, 0.45046408, ..., 3.82277224,
         3.82277224, 3.82277224]],

       [[0.50630869, 0.50630869, 0.50630869, ..., 4.12405982,
         4.12405982, 4.12405982],
        [0.48225079, 0.48225079, 0.48225079, ..., 4.3178065 ,
         4.3178065 , 4.3178065 ],
        [0.40210585, 0.40210585, 0.40210585, ..., 3.82710494,
         3.82710494, 3.82710494],
        ...,
        [0.45680392, 0.45680392, 0.45680392, ..., 4.09999256,
         4.09999256, 4.09999256],
        [0.45680392, 0.45680392, 0.45680392, ..., 4.09999256,
         4.09999256, 4.09999256],
        [0.48184082, 0.48184082, 0.48184082, ..., 4.0575285 ,
         4.0575285 , 4.0575285 ]]])</pre></div></li></ul></div></li><li class='xr-section-item'><input id='section-00ba8beb-fa69-4a60-adbd-35b04f7377d7' class='xr-section-summary-in' type='checkbox'  ><label for='section-00ba8beb-fa69-4a60-adbd-35b04f7377d7' class='xr-section-summary' >Indexes: <span>(4)</span></label><div class='xr-section-inline-details'></div><div class='xr-section-details'><ul class='xr-var-list'><li class='xr-var-item'><div class='xr-index-name'><div>chain</div></div><div class='xr-index-preview'>PandasIndex</div><input type='checkbox' disabled/><label></label><input id='index-55f334bd-b030-4eec-ba36-ec2a70ddf143' class='xr-index-data-in' type='checkbox'/><label for='index-55f334bd-b030-4eec-ba36-ec2a70ddf143' title='Show/Hide index repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-index-data'><pre>PandasIndex(Index([0, 1, 2, 3, 4, 5], dtype=&#x27;int64&#x27;, name=&#x27;chain&#x27;))</pre></div></li><li class='xr-var-item'><div class='xr-index-name'><div>draw</div></div><div class='xr-index-preview'>PandasIndex</div><input type='checkbox' disabled/><label></label><input id='index-e5ab3a2c-b239-4bbe-b05e-1a4955a404e8' class='xr-index-data-in' type='checkbox'/><label for='index-e5ab3a2c-b239-4bbe-b05e-1a4955a404e8' title='Show/Hide index repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-index-data'><pre>PandasIndex(Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999],
      dtype=&#x27;int64&#x27;, name=&#x27;draw&#x27;, length=2000))</pre></div></li><li class='xr-var-item'><div class='xr-index-name'><div>Treatment_dim</div></div><div class='xr-index-preview'>PandasIndex</div><input type='checkbox' disabled/><label></label><input id='index-566b37b0-63cd-4758-987c-8d5876cb417b' class='xr-index-data-in' type='checkbox'/><label for='index-566b37b0-63cd-4758-987c-8d5876cb417b' title='Show/Hide index repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-index-data'><pre>PandasIndex(Index([&#x27;Trt&#x27;], dtype=&#x27;object&#x27;, name=&#x27;Treatment_dim&#x27;))</pre></div></li><li class='xr-var-item'><div class='xr-index-name'><div>__obs__</div></div><div class='xr-index-preview'>PandasIndex</div><input type='checkbox' disabled/><label></label><input id='index-bab955db-a383-44c3-8ab1-b47d56020904' class='xr-index-data-in' type='checkbox'/><label for='index-bab955db-a383-44c3-8ab1-b47d56020904' title='Show/Hide index repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-index-data'><pre>PandasIndex(Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       662, 663, 664, 665, 666, 667, 668, 669, 670, 671],
      dtype=&#x27;int64&#x27;, name=&#x27;__obs__&#x27;, length=672))</pre></div></li></ul></div></li><li class='xr-section-item'><input id='section-b53eb709-d45b-4cf5-9d59-99b30a81b53a' class='xr-section-summary-in' type='checkbox'  checked><label for='section-b53eb709-d45b-4cf5-9d59-99b30a81b53a' class='xr-section-summary' >Attributes: <span>(8)</span></label><div class='xr-section-inline-details'></div><div class='xr-section-details'><dl class='xr-attrs'><dt><span>created_at :</span></dt><dd>2025-07-01T16:14:29.892205+00:00</dd><dt><span>arviz_version :</span></dt><dd>0.21.0</dd><dt><span>inference_library :</span></dt><dd>pymc</dd><dt><span>inference_library_version :</span></dt><dd>5.22.0</dd><dt><span>sampling_time :</span></dt><dd>18.31052279472351</dd><dt><span>tuning_steps :</span></dt><dd>500</dd><dt><span>modeling_interface :</span></dt><dd>bambi</dd><dt><span>modeling_interface_version :</span></dt><dd>0.15.0</dd></dl></div></li></ul></div></div>
<div class="sourceCode" id="cb95"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb95-1"><a href="GLMMsPython.html#cb95-1" tabindex="-1"></a>bmbPreds1nb[<span class="st">&quot;preds&quot;</span>] <span class="op">=</span> post1nb.mean(dim<span class="op">=</span>[<span class="st">&quot;chain&quot;</span>, <span class="st">&quot;draw&quot;</span>])[<span class="st">&quot;mu&quot;</span>].values</span>
<span id="cb95-2"><a href="GLMMsPython.html#cb95-2" tabindex="-1"></a>bmbPreds1nb[<span class="st">&quot;lowerCI&quot;</span>] <span class="op">=</span> post1nb.quantile(dim<span class="op">=</span>[<span class="st">&quot;chain&quot;</span>, <span class="st">&quot;draw&quot;</span>], q <span class="op">=</span> <span class="fl">0.025</span>)[<span class="st">&quot;mu&quot;</span>].values</span>
<span id="cb95-3"><a href="GLMMsPython.html#cb95-3" tabindex="-1"></a>bmbPreds1nb[<span class="st">&quot;upperCI&quot;</span>] <span class="op">=</span> post1nb.quantile(dim<span class="op">=</span>[<span class="st">&quot;chain&quot;</span>, <span class="st">&quot;draw&quot;</span>], q <span class="op">=</span> <span class="fl">0.975</span>)[<span class="st">&quot;mu&quot;</span>].values</span>
<span id="cb95-4"><a href="GLMMsPython.html#cb95-4" tabindex="-1"></a>bmbPreds1nb.describe()</span></code></pre></div>
<pre><code>##            TrapID   Longitude    Latitude                 TransplantDate  \
## count  672.000000  672.000000  672.000000                            672   
## mean   152.500000  108.684570   -6.895572  2023-08-16 01:25:42.857142784   
## min    101.000000  106.451339   -7.421778            2023-07-24 00:00:00   
## 25%    102.750000  106.653911   -7.242430            2023-08-06 00:00:00   
## 50%    152.500000  107.809442   -6.876379            2023-08-12 00:00:00   
## 75%    202.250000  110.998138   -6.740433            2023-08-26 00:00:00   
## max    204.000000  111.621353   -6.178671            2023-09-09 00:00:00   
## std     50.049752    2.101653    0.417043                            NaN   
## 
##                      TrapInstallDate                DispInstallDate  \
## count                            672                            440   
## mean   2023-08-20 08:34:17.142857216  2023-08-20 04:34:54.545454592   
## min              2023-08-04 00:00:00            2023-08-04 00:00:00   
## 25%              2023-08-11 00:00:00            2023-08-11 00:00:00   
## 50%              2023-08-17 00:00:00            2023-08-16 00:00:00   
## 75%              2023-08-31 00:00:00            2023-08-31 00:00:00   
## max              2023-09-10 00:00:00            2023-09-10 00:00:00   
## std                              NaN                            NaN   
## 
##        AssessmentNumber                   SamplingDate        nYSB  \
## count        672.000000                            672  672.000000   
## mean           4.750000  2023-10-06 23:02:08.571428608   22.558036   
## min            1.000000            2023-08-14 00:00:00    0.000000   
## 25%            3.000000            2023-09-15 18:00:00    2.000000   
## 50%            5.000000            2023-10-06 00:00:00    5.000000   
## 75%            7.000000            2023-10-28 00:00:00   17.000000   
## max           10.000000            2023-11-24 00:00:00  429.000000   
## std            2.498882                            NaN   51.304964   
## 
##        DaysOfCatch        DATI        DADI         DAT  mothsperday  \
## count        672.0  672.000000  440.000000  672.000000   672.000000   
## mean           1.0   47.602679   48.038636   51.900298     2.266169   
## min            1.0    8.000000   10.000000   11.000000     0.000000   
## 25%            1.0   29.750000   30.000000   31.000000     0.200000   
## 50%            1.0   50.000000   50.000000   52.000000     0.500000   
## 75%            1.0   70.000000   70.000000   73.000000     1.706818   
## max            1.0  101.000000  101.000000  114.000000    42.900000   
## std            0.0   25.120304   25.332340   25.695521     5.118438   
## 
##        exp_values     lowerCI     upperCI       preds  
## count  672.000000  672.000000  672.000000  672.000000  
## mean     2.265697    1.984167    2.597330    2.270442  
## min      0.467019    0.407712    0.540182    0.470203  
## 25%      0.467019    0.407712    0.540182    0.470203  
## 50%      2.265697    1.984167    2.597330    2.270442  
## 75%      4.064375    3.560621    4.654479    4.070682  
## max      4.064375    3.560621    4.654479    4.070682  
## std      1.800018    1.577629    2.058681    1.801580</code></pre>
<div class="sourceCode" id="cb97"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb97-1"><a href="GLMMsPython.html#cb97-1" tabindex="-1"></a>plot1nb <span class="op">=</span> (ggplot(bmbPreds1nb, </span>
<span id="cb97-2"><a href="GLMMsPython.html#cb97-2" tabindex="-1"></a>                aes(x <span class="op">=</span> <span class="st">&#39;DATI&#39;</span>, y<span class="op">=</span><span class="st">&#39;preds&#39;</span>, color <span class="op">=</span> <span class="st">&#39;Treatment&#39;</span>)) <span class="op">+</span></span>
<span id="cb97-3"><a href="GLMMsPython.html#cb97-3" tabindex="-1"></a>        geom_line() <span class="op">+</span></span>
<span id="cb97-4"><a href="GLMMsPython.html#cb97-4" tabindex="-1"></a>        geom_ribbon(aes(ymin <span class="op">=</span> <span class="st">&#39;lowerCI&#39;</span>, ymax <span class="op">=</span> <span class="st">&#39;upperCI&#39;</span>, fill <span class="op">=</span> <span class="st">&#39;Treatment&#39;</span>),</span>
<span id="cb97-5"><a href="GLMMsPython.html#cb97-5" tabindex="-1"></a>              alpha <span class="op">=</span> <span class="fl">0.3</span>) <span class="op">+</span></span>
<span id="cb97-6"><a href="GLMMsPython.html#cb97-6" tabindex="-1"></a>        geom_point(aes(x<span class="op">=</span><span class="st">&#39;DATI&#39;</span>, y<span class="op">=</span><span class="st">&#39;mothsperday&#39;</span>, color <span class="op">=</span> <span class="st">&#39;Treatment&#39;</span>), </span>
<span id="cb97-7"><a href="GLMMsPython.html#cb97-7" tabindex="-1"></a>            data <span class="op">=</span> mean_cts, size <span class="op">=</span> <span class="fl">1.1</span>) <span class="op">+</span></span>
<span id="cb97-8"><a href="GLMMsPython.html#cb97-8" tabindex="-1"></a>        facet_wrap([<span class="st">&#39;Location&#39;</span>], scales <span class="op">=</span> <span class="st">&quot;free_y&quot;</span>) <span class="op">+</span></span>
<span id="cb97-9"><a href="GLMMsPython.html#cb97-9" tabindex="-1"></a>        scale_color_manual(values <span class="op">=</span> mycolors) <span class="op">+</span></span>
<span id="cb97-10"><a href="GLMMsPython.html#cb97-10" tabindex="-1"></a>        scale_fill_manual(values <span class="op">=</span> mycolors) <span class="op">+</span></span>
<span id="cb97-11"><a href="GLMMsPython.html#cb97-11" tabindex="-1"></a>        labs(title <span class="op">=</span> <span class="st">&quot;Bayes neg binom GLM&quot;</span>,</span>
<span id="cb97-12"><a href="GLMMsPython.html#cb97-12" tabindex="-1"></a>             subtitle <span class="op">=</span> <span class="st">&quot;Lines are predictions, points are the data&quot;</span>))</span>
<span id="cb97-13"><a href="GLMMsPython.html#cb97-13" tabindex="-1"></a><span class="co"># plot1nb.draw(True)</span></span>
<span id="cb97-14"><a href="GLMMsPython.html#cb97-14" tabindex="-1"></a>plot1nb.show()</span></code></pre></div>
<p><img src="03-GLMMsInPython_files/figure-html/nbBambi1Output-5.png" width="100%" /></p>
<div class="sourceCode" id="cb98"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb98-1"><a href="GLMMsPython.html#cb98-1" tabindex="-1"></a><span class="co"># plot1nb.save(filename=&#39;plot1nb.png&#39;, path=&#39;output/&#39;)</span></span></code></pre></div>
<p>The Bayesian parameter estimates match very closely to the frequentist estimates. This is expected, but reassuring that we have built the correct foundation for the more complicated models to come. The first summary output is from the Bayesian model; the second is from the frequentist fit. (Note that in the fequentitst fit, they summarize the inverse shape parameter compared to the bambi fit.)</p>
<p>Comparisons of TR predictions and predicted moth count values can be found at the end of the page.</p>
</div>
<div id="bayesian-pymc-models-python" class="section level3 hasAnchor" number="4.4.4">
<h3><span class="header-section-number">4.4.4</span> Bayesian (PyMC) models– Python<a href="GLMMsPython.html#bayesian-pymc-models-python" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For most needs, the <code>bambi</code> module should suffice. However, when I want to build my complicated non-linear function with multi-dimensional Gaussian Processes, I am going to need a more foundational module– PyMC. Therefore, I also build the models using this module. Learning PyMC will also help with extracting derived parameters and predictions, etc. from bambi.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb99-1"><a href="GLMMsPython.html#cb99-1" tabindex="-1"></a><span class="co"># NB Bayes:</span></span>
<span id="cb99-2"><a href="GLMMsPython.html#cb99-2" tabindex="-1"></a><span class="co">#https://discourse.pymc.io/t/biased-results-from-poisson-regression-model/4349/5</span></span>
<span id="cb99-3"><a href="GLMMsPython.html#cb99-3" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb99-4"><a href="GLMMsPython.html#cb99-4" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb99-5"><a href="GLMMsPython.html#cb99-5" tabindex="-1"></a></span>
<span id="cb99-6"><a href="GLMMsPython.html#cb99-6" tabindex="-1"></a><span class="im">from</span> formulae <span class="im">import</span> design_matrices</span>
<span id="cb99-7"><a href="GLMMsPython.html#cb99-7" tabindex="-1"></a><span class="im">import</span> pymc <span class="im">as</span> pm</span>
<span id="cb99-8"><a href="GLMMsPython.html#cb99-8" tabindex="-1"></a><span class="co"># Create the design matrix using formulae</span></span>
<span id="cb99-9"><a href="GLMMsPython.html#cb99-9" tabindex="-1"></a><span class="co"># Wrapping the variable in &#39;C()&#39; enforces categorical values, with the first entry as the reference</span></span>
<span id="cb99-10"><a href="GLMMsPython.html#cb99-10" tabindex="-1"></a>dm <span class="op">=</span> design_matrices(<span class="st">&#39;nYSB ~ C(Treatment)&#39;</span>, data<span class="op">=</span>datP, na_action<span class="op">=</span><span class="st">&#39;error&#39;</span>)</span>
<span id="cb99-11"><a href="GLMMsPython.html#cb99-11" tabindex="-1"></a><span class="co"># print(dm.common.as_dataframe().head())</span></span>
<span id="cb99-12"><a href="GLMMsPython.html#cb99-12" tabindex="-1"></a></span>
<span id="cb99-13"><a href="GLMMsPython.html#cb99-13" tabindex="-1"></a><span class="co"># Expand out into X and y</span></span>
<span id="cb99-14"><a href="GLMMsPython.html#cb99-14" tabindex="-1"></a>X <span class="op">=</span> dm.common.as_dataframe()</span>
<span id="cb99-15"><a href="GLMMsPython.html#cb99-15" tabindex="-1"></a>y <span class="op">=</span> dm.response.as_dataframe().squeeze() <span class="co"># This ensures y is 1-dimensional. </span></span>
<span id="cb99-16"><a href="GLMMsPython.html#cb99-16" tabindex="-1"></a></span>
<span id="cb99-17"><a href="GLMMsPython.html#cb99-17" tabindex="-1"></a>DaysOfCatch <span class="op">=</span> datP[<span class="st">&#39;DaysOfCatch&#39;</span>]</span>
<span id="cb99-18"><a href="GLMMsPython.html#cb99-18" tabindex="-1"></a></span>
<span id="cb99-19"><a href="GLMMsPython.html#cb99-19" tabindex="-1"></a><span class="co"># Create labelled coords which help the model keep track of everything(i.e., use factor names)</span></span>
<span id="cb99-20"><a href="GLMMsPython.html#cb99-20" tabindex="-1"></a>c <span class="op">=</span> {<span class="st">&#39;predictors&#39;</span>: X.columns, <span class="co"># Model now aware of number of and labels of predictors</span></span>
<span id="cb99-21"><a href="GLMMsPython.html#cb99-21" tabindex="-1"></a>     <span class="st">&#39;N&#39;</span>: <span class="bu">range</span>(<span class="bu">len</span>(y))} <span class="co"># and number of observations</span></span>
<span id="cb99-22"><a href="GLMMsPython.html#cb99-22" tabindex="-1"></a></span>
<span id="cb99-23"><a href="GLMMsPython.html#cb99-23" tabindex="-1"></a><span class="cf">with</span> pm.Model(coords <span class="op">=</span> c) <span class="im">as</span> model_pymc1nb:</span>
<span id="cb99-24"><a href="GLMMsPython.html#cb99-24" tabindex="-1"></a>    <span class="co"># Set the data, and convert to NumPy arrays (to use matrix multiplication</span></span>
<span id="cb99-25"><a href="GLMMsPython.html#cb99-25" tabindex="-1"></a>    Xdata <span class="op">=</span> pm.Data(<span class="st">&#39;Xdata&#39;</span>, X.to_numpy())</span>
<span id="cb99-26"><a href="GLMMsPython.html#cb99-26" tabindex="-1"></a>    Ydata <span class="op">=</span> pm.Data(<span class="st">&#39;Ydata&#39;</span>, y.to_numpy())</span>
<span id="cb99-27"><a href="GLMMsPython.html#cb99-27" tabindex="-1"></a>    </span>
<span id="cb99-28"><a href="GLMMsPython.html#cb99-28" tabindex="-1"></a>    <span class="co"># priors</span></span>
<span id="cb99-29"><a href="GLMMsPython.html#cb99-29" tabindex="-1"></a>    <span class="co"># factor_coefs = pm.Normal(&#39;factor_coefs&#39;, mu=0, sigma=2, shape=len(X.columns))    </span></span>
<span id="cb99-30"><a href="GLMMsPython.html#cb99-30" tabindex="-1"></a>    beta <span class="op">=</span> pm.Normal(<span class="st">&#39;beta&#39;</span>, mu<span class="op">=</span><span class="dv">0</span>, sigma<span class="op">=</span><span class="dv">2</span>, dims <span class="op">=</span> <span class="st">&#39;predictors&#39;</span>)</span>
<span id="cb99-31"><a href="GLMMsPython.html#cb99-31" tabindex="-1"></a>    alpha <span class="op">=</span> pm.HalfCauchy(<span class="st">&#39;alpha&#39;</span>, beta <span class="op">=</span> <span class="dv">1</span>)</span>
<span id="cb99-32"><a href="GLMMsPython.html#cb99-32" tabindex="-1"></a></span>
<span id="cb99-33"><a href="GLMMsPython.html#cb99-33" tabindex="-1"></a>    <span class="co"># TR derived parameter:</span></span>
<span id="cb99-34"><a href="GLMMsPython.html#cb99-34" tabindex="-1"></a>    TR <span class="op">=</span> pm.Deterministic(<span class="st">&#39;TR&#39;</span>, <span class="dv">100</span> <span class="op">-</span> <span class="dv">100</span> <span class="op">*</span> np.exp(beta[<span class="dv">1</span>]))</span>
<span id="cb99-35"><a href="GLMMsPython.html#cb99-35" tabindex="-1"></a>    </span>
<span id="cb99-36"><a href="GLMMsPython.html#cb99-36" tabindex="-1"></a>    <span class="co"># likelihood:</span></span>
<span id="cb99-37"><a href="GLMMsPython.html#cb99-37" tabindex="-1"></a>    mu <span class="op">=</span> pm.math.exp(Xdata <span class="op">@</span> beta <span class="op">+</span> <span class="co"># pm.math.dot(X, factor_coefs) + #@ operator is for matrix multiplication </span></span>
<span id="cb99-38"><a href="GLMMsPython.html#cb99-38" tabindex="-1"></a>                     np.log(DaysOfCatch)) </span>
<span id="cb99-39"><a href="GLMMsPython.html#cb99-39" tabindex="-1"></a>    pm.NegativeBinomial(<span class="st">&#39;y&#39;</span>, mu<span class="op">=</span>mu, alpha <span class="op">=</span> alpha, observed<span class="op">=</span>Ydata)</span>
<span id="cb99-40"><a href="GLMMsPython.html#cb99-40" tabindex="-1"></a>    </span>
<span id="cb99-41"><a href="GLMMsPython.html#cb99-41" tabindex="-1"></a>    <span class="co"># Sample according to your specifications, but tune for longer and take fewer draws</span></span>
<span id="cb99-42"><a href="GLMMsPython.html#cb99-42" tabindex="-1"></a>    pymc1nb <span class="op">=</span> pm.sample(draws<span class="op">=</span><span class="dv">1000</span>, tune<span class="op">=</span><span class="dv">3000</span>, cores<span class="op">=</span><span class="dv">4</span>, random_seed<span class="op">=</span><span class="dv">45</span>, step<span class="op">=</span>pm.NUTS())<span class="co">#Metropolis())</span></span>
<span id="cb99-43"><a href="GLMMsPython.html#cb99-43" tabindex="-1"></a>    <span class="co"># pymc1nb is called &#39;trace&#39; in lots of the help files</span></span>
<span id="cb99-44"><a href="GLMMsPython.html#cb99-44" tabindex="-1"></a></span>
<span id="cb99-45"><a href="GLMMsPython.html#cb99-45" tabindex="-1"></a></span>
<span id="cb99-46"><a href="GLMMsPython.html#cb99-46" tabindex="-1"></a><span class="im">import</span> pickle <span class="co"># to save PyMC object to file.</span></span>
<span id="cb99-47"><a href="GLMMsPython.html#cb99-47" tabindex="-1"></a>filename <span class="op">=</span> <span class="st">&#39;output/respymc1nb.pkl&#39;</span></span>
<span id="cb99-48"><a href="GLMMsPython.html#cb99-48" tabindex="-1"></a><span class="co"># save bambi object to file.</span></span>
<span id="cb99-49"><a href="GLMMsPython.html#cb99-49" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(filename, <span class="st">&#39;wb&#39;</span>) <span class="im">as</span> <span class="bu">file</span>:</span>
<span id="cb99-50"><a href="GLMMsPython.html#cb99-50" tabindex="-1"></a>    pickle.dump(pymc1nb, <span class="bu">file</span>)</span></code></pre></div>
<div class="sourceCode" id="cb100"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb100-1"><a href="GLMMsPython.html#cb100-1" tabindex="-1"></a><span class="co"># Load the object from the file</span></span>
<span id="cb100-2"><a href="GLMMsPython.html#cb100-2" tabindex="-1"></a><span class="im">import</span> pickle</span>
<span id="cb100-3"><a href="GLMMsPython.html#cb100-3" tabindex="-1"></a>filename <span class="op">=</span> <span class="st">&#39;output/respymc1nb.pkl&#39;</span></span>
<span id="cb100-4"><a href="GLMMsPython.html#cb100-4" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(filename, <span class="st">&#39;rb&#39;</span>) <span class="im">as</span> <span class="bu">file</span>:</span>
<span id="cb100-5"><a href="GLMMsPython.html#cb100-5" tabindex="-1"></a>    pymc1nb <span class="op">=</span> pickle.load(<span class="bu">file</span>)</span>
<span id="cb100-6"><a href="GLMMsPython.html#cb100-6" tabindex="-1"></a></span>
<span id="cb100-7"><a href="GLMMsPython.html#cb100-7" tabindex="-1"></a><span class="co"># summary stats</span></span>
<span id="cb100-8"><a href="GLMMsPython.html#cb100-8" tabindex="-1"></a><span class="bu">print</span>(az.summary(pymc1nb))</span></code></pre></div>
<pre><code>##                            mean     sd  hdi_3%  hdi_97%  mcse_mean  mcse_sd  \
## beta[Intercept]           1.402  0.067   1.279    1.532      0.001    0.001   
## beta[C(Treatment)[Trt]]  -2.160  0.099  -2.348   -1.981      0.002    0.001   
## alpha                     0.655  0.035   0.591    0.720      0.001    0.001   
## TR                       88.406  1.141  86.308   90.527      0.024    0.017   
## 
##                          ess_bulk  ess_tail  r_hat  
## beta[Intercept]            2275.0    2726.0    1.0  
## beta[C(Treatment)[Trt]]    2184.0    2559.0    1.0  
## alpha                      3165.0    2350.0    1.0  
## TR                         2184.0    2559.0    1.0</code></pre>
<div class="sourceCode" id="cb102"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb102-1"><a href="GLMMsPython.html#cb102-1" tabindex="-1"></a><span class="co"># CALC TR!</span></span>
<span id="cb102-2"><a href="GLMMsPython.html#cb102-2" tabindex="-1"></a><span class="bu">print</span>(az.summary(pymc1nb, var_names<span class="op">=</span>[<span class="st">&#39;TR&#39;</span>]))</span></code></pre></div>
<pre><code>##       mean     sd  hdi_3%  hdi_97%  mcse_mean  mcse_sd  ess_bulk  ess_tail  \
## TR  88.406  1.141  86.308   90.527      0.024    0.017    2184.0    2559.0   
## 
##     r_hat  
## TR    1.0</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb104-1"><a href="GLMMsPython.html#cb104-1" tabindex="-1"></a><span class="co"># outTR1nb = round(TR1nb.quantile(q=[0.025, 0.5, 0.975]).to_pandas())</span></span></code></pre></div>
</div>
</div>
<div id="summary-of-estimates-1" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> Summary of estimates<a href="GLMMsPython.html#summary-of-estimates-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="compare-tr-estimates" class="section level3 hasAnchor" number="4.5.1">
<h3><span class="header-section-number">4.5.1</span> Compare TR estimates<a href="GLMMsPython.html#compare-tr-estimates" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Here, the trapping reduction estimates from all of the models are compared. As expected, the median TR estimates are very close from model to model, but the uncertainty in that estimate increase (i.e., the confidence/credible intervals get wider) when we properly account for the correlations in our data.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb105-1"><a href="GLMMsPython.html#cb105-1" tabindex="-1"></a>data <span class="op">=</span> np.array([<span class="bu">round</span>(TR_1nb.quantile(q<span class="op">=</span>[<span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span>]))) </span>
<span id="cb105-2"><a href="GLMMsPython.html#cb105-2" tabindex="-1"></a>                 <span class="co"># round(TR2nb.quantile(q=[0.025, 0.5, 0.975])), </span></span>
<span id="cb105-3"><a href="GLMMsPython.html#cb105-3" tabindex="-1"></a>                 <span class="co"># round(TR3nb.quantile(q=[0.025, 0.5, 0.975])),</span></span>
<span id="cb105-4"><a href="GLMMsPython.html#cb105-4" tabindex="-1"></a>                 <span class="co"># round(TR4nb.quantile(q=[0.025, 0.5, 0.975]))])</span></span>
<span id="cb105-5"><a href="GLMMsPython.html#cb105-5" tabindex="-1"></a></span>
<span id="cb105-6"><a href="GLMMsPython.html#cb105-6" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame(data, columns <span class="op">=</span> [<span class="st">&quot;TR&quot;</span>, <span class="st">&quot;lowerCI&quot;</span>, <span class="st">&quot;upperCI&quot;</span>])</span>
<span id="cb105-7"><a href="GLMMsPython.html#cb105-7" tabindex="-1"></a>df[<span class="st">&quot;Model_name&quot;</span>] <span class="op">=</span> [<span class="st">&quot;GLM&quot;</span>, <span class="st">&quot;GLMM (location)&quot;</span>, <span class="st">&quot;GLMM (location, date)&quot;</span>, <span class="st">&quot;GLMM (location) with GP&quot;</span>]</span>
<span id="cb105-8"><a href="GLMMsPython.html#cb105-8" tabindex="-1"></a>df[<span class="st">&quot;Distribution&quot;</span>] <span class="op">=</span> [<span class="st">&quot;Neg Binomial&quot;</span>, <span class="st">&quot;Neg Binomial&quot;</span>, <span class="st">&quot;Neg Binomial&quot;</span>, <span class="st">&quot;Neg Binomial&quot;</span>]</span>
<span id="cb105-9"><a href="GLMMsPython.html#cb105-9" tabindex="-1"></a>df[<span class="st">&quot;Framework&quot;</span>] <span class="op">=</span> [<span class="st">&quot;Bayesian&quot;</span>, <span class="st">&quot;Bayesian&quot;</span>, <span class="st">&quot;Bayesian&quot;</span>, <span class="st">&quot;Bayesian&quot;</span>]</span>
<span id="cb105-10"><a href="GLMMsPython.html#cb105-10" tabindex="-1"></a><span class="bu">print</span>(df[[<span class="st">&quot;Framework&quot;</span>, <span class="st">&quot;Distribution&quot;</span>, <span class="st">&quot;Model_name&quot;</span>, <span class="st">&quot;TR&quot;</span>, <span class="st">&quot;lowerCI&quot;</span>, <span class="st">&quot;upperCI&quot;</span>]])</span></code></pre></div>
</div>
<div id="compare-coefficients-1" class="section level3 hasAnchor" number="4.5.2">
<h3><span class="header-section-number">4.5.2</span> Compare coefficients<a href="GLMMsPython.html#compare-coefficients-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Because TR is a non-linear function of <span class="math inline">\(\beta_1\)</span>, the differences in the model output get slightly distorted from the transformation. Thereofre, the <span class="math inline">\(\beta_1\)</span> coefficients are displayed as well:</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb106-1"><a href="GLMMsPython.html#cb106-1" tabindex="-1"></a>dfB <span class="op">=</span> pd.concat([az.summary(idata_bmb1nb, var_names<span class="op">=</span>[<span class="st">&quot;Treatment&quot;</span>])[[<span class="st">&quot;mean&quot;</span>, <span class="st">&quot;sd&quot;</span>]],</span>
<span id="cb106-2"><a href="GLMMsPython.html#cb106-2" tabindex="-1"></a>az.summary(idata_bmb2nb, var_names<span class="op">=</span>[<span class="st">&quot;Treatment&quot;</span>])[[<span class="st">&quot;mean&quot;</span>, <span class="st">&quot;sd&quot;</span>]]], ignore_index<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb106-3"><a href="GLMMsPython.html#cb106-3" tabindex="-1"></a></span>
<span id="cb106-4"><a href="GLMMsPython.html#cb106-4" tabindex="-1"></a>dfB <span class="op">=</span> pd.concat([dfB,</span>
<span id="cb106-5"><a href="GLMMsPython.html#cb106-5" tabindex="-1"></a>az.summary(idata_bmb3nb, var_names<span class="op">=</span>[<span class="st">&quot;Treatment&quot;</span>])[[<span class="st">&quot;mean&quot;</span>, <span class="st">&quot;sd&quot;</span>]]], ignore_index<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb106-6"><a href="GLMMsPython.html#cb106-6" tabindex="-1"></a>dfB <span class="op">=</span> pd.concat([dfB,</span>
<span id="cb106-7"><a href="GLMMsPython.html#cb106-7" tabindex="-1"></a>az.summary(idata_bmb4nb, var_names<span class="op">=</span>[<span class="st">&quot;Treatment&quot;</span>])[[<span class="st">&quot;mean&quot;</span>, <span class="st">&quot;sd&quot;</span>]]], ignore_index<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb106-8"><a href="GLMMsPython.html#cb106-8" tabindex="-1"></a>dfB</span>
<span id="cb106-9"><a href="GLMMsPython.html#cb106-9" tabindex="-1"></a></span>
<span id="cb106-10"><a href="GLMMsPython.html#cb106-10" tabindex="-1"></a>dfB[<span class="st">&quot;Model_name&quot;</span>] <span class="op">=</span> [<span class="st">&quot;GLM&quot;</span>, <span class="st">&quot;GLMM (location)&quot;</span>, <span class="st">&quot;GLMM (location, date)&quot;</span>, <span class="st">&quot;GLMM (location) with GP&quot;</span>]</span>
<span id="cb106-11"><a href="GLMMsPython.html#cb106-11" tabindex="-1"></a>dfB[<span class="st">&quot;Distribution&quot;</span>] <span class="op">=</span> [<span class="st">&quot;Neg Binomial&quot;</span>, <span class="st">&quot;Neg Binomial&quot;</span>, <span class="st">&quot;Neg Binomial&quot;</span>, <span class="st">&quot;Neg Binomial&quot;</span>]</span>
<span id="cb106-12"><a href="GLMMsPython.html#cb106-12" tabindex="-1"></a>dfB[<span class="st">&quot;Framework&quot;</span>] <span class="op">=</span> [<span class="st">&quot;Bayesian&quot;</span>, <span class="st">&quot;Bayesian&quot;</span>, <span class="st">&quot;Bayesian&quot;</span>, <span class="st">&quot;Bayesian&quot;</span>]</span>
<span id="cb106-13"><a href="GLMMsPython.html#cb106-13" tabindex="-1"></a><span class="bu">print</span>(dfB[[<span class="st">&quot;Framework&quot;</span>, <span class="st">&quot;Distribution&quot;</span>, <span class="st">&quot;Model_name&quot;</span>, <span class="st">&quot;mean&quot;</span>, <span class="st">&quot;sd&quot;</span>]])</span></code></pre></div>
</div>
<div id="plot-comparisons-1" class="section level3 hasAnchor" number="4.5.3">
<h3><span class="header-section-number">4.5.3</span> Plot comparisons<a href="GLMMsPython.html#plot-comparisons-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Unfortunately, a drawback of using plotnine module is that you cannot readily draw figures sid-by-side.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="GLMMsR.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="NonlinearR.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
